### ISSUE TITLE
Resource embedding: how can I filter on sub relations?

### ISSUE THREAD

**Issue by ppooppoo** [begriffs/postgrest#1018]
Hi,

I have a question regarding resource embedding. I have a table `team` and a table `player`. A player can belong to one or more teams.

I want to express something like the following:

    http://localhost:3000/team?select=identifier,name,player(identifier,name)&or=(player.name.eq.Messi,player.name.eq.Suarez)

So I want all teams and for each team, I want the players `Messi` and `Suarez` (if they belong to that team).

That doesn't seem possible with the URL above, I am getting parse exceptions. Is this possible?

Thanks a lot!

**Comment by ppooppoo** [comment]
Side question: Is it also possible to retrieve only the teams which have `Messi` or `Suarez` in their player list? I can of course invert the query and start with `/player`, but let's assume I want to start with `/team`.

**Comment by ppooppoo** [comment]
Regarding my first question, I managed to get it working with `&player.name=in.(Messi,Suarez)`. But I am still curious how to do it with an `or` so I can filter on multiple conditions. For example: `players with name Messi/Suarez or players with active set to true`. How can I do that?

**Comment by begriffs** [comment]
As described in https://postgrest.com/en/v4.3/api.html#embedded-filters-and-order, it's not possible to retrieve only the teams which have Messi or Suarez. Selecting `team` and filtering by `player.name` would just end up giving you the same teams as before, but some of them would have empty player lists because the filter applies inside the embedded list.

You can use [stored procedures](https://postgrest.com/en/v4.3/api.html#stored-procedures) for complex custom logic, or make a view in the db and select/filter that with postgrest.

**Comment by ppooppoo** [comment]
@begriffs Thanks for feedback. I will try it out with stored procedures/views. Very interesting to play with!

**Comment by sunbing81** [comment]
My two cents.

In our application scenarios, the clients work typically with wide tables which can be different joining set of several base data models. Resource embedding enables great flexibilities to retreive **all** (or filtered by top relation conditions) data, since the client can choose whether or not to embed how many resources (tables) according to the usage. Only the underlying base models need to be exposed.

But it is so common that the clients need to filter records by sub-relation conditions. The users want to list only the movies directed by Clint Eastwood; they want to list only the factories located in countries of Asia, etc.. Sadly, resource embedding simply doesn't allow filtering parent records by children conditions. IMHO, this limits the usage of resource embedding quite a bit. All the work-arounds need extra maintanence and also expose a lot redundent access points.

**Comment by steve-chavez** [comment]
@sunbing81 Progress on this is being tracked at https://github.com/PostgREST/postgrest/issues/1075.

**Comment by sunbing81** [comment]
I do realize it is quite difficult to handle the case of to-N relationship. But for to-1 relationship, I think there might be a way.

```sql
CREATE TABLE director (
  name text PRIMARY KEY
);

CREATE TABLE movie (
  titile text,
  director_name text references director(name)
); 
```

Assume the movie-director relationship is to-1 (a movie can only have one director, but not necessarily vice versa). A request of
```
GET /movie?select=*,director(*)&director.name=directorA
```
may response with
```json
[
  {"title": "movieA", "name": "directorA", "director": [{"name": "directorA"}]},
  {"title": "movieB", "name": "directorB", "director": null}
]
```.

It would be sweet that postgrest could support the following syntax:
```
GET /movie?select=*,director(*)&director.name=directorA&director=not.is.null
```

Ideally, it should response with
```json
[
  {"title": "movieA", "name": "directorA", "director": [{"name": "directorA"}]}
]
```.

Would that be of any possibility?

**Comment by sunbing81** [comment]
> @sunbing81 Progress on this is being tracked at #1075.

My bad, didn't dig all related issues.
