### ISSUE TITLE
Environment variables in the configuration file

### ISSUE THREAD

**Issue by TAQ2** [begriffs/postgrest#1064]
Hello,

I am on the lastest version of postgrest and I work in a team, in which we all use individual databases. I am wondering if I can set up an environment variable so that a dev must pass in their db uri to make postgrest work, while keeping values of the schema or the jwt-secret the same. Any ideas how I can do this?

Thanks!

**Comment by ruslantalpa** [comment]
So you are saying each dev has his own "config file" for his postgrest deployment?
OR are you saying you want to run a single PostgREST instance and have it connect to different database depending on what developer is accessing it? (not possible)

**Comment by TAQ2** [comment]
Thanks for getting back to me! Yes the former, each dev has their own config file, but the only difference will be the db-uri. Everything else must stay the same

**Comment by ruslantalpa** [comment]
You could use docker to be able to use env vars but i don't see a big difference from each dev having his own config file and running his instance of postgrest

**Comment by TAQ2** [comment]
yeah makes sense, I guess I was trying to control what is in this config file (to avoid bugs) but as you say each dev with a config file is not that big of a deal :)

**Comment by steve-chavez** [comment]
There's been support for env vars in the config for a while now, since [v0.4.2.0](https://github.com/begriffs/postgrest/releases/tag/v0.4.2.0)("Env var interpolation in config file" in CHANGELOG), you have to quote the config value like in `db-uri = "$(DB_URI)"`, there's an example here https://github.com/begriffs/postgrest/blob/master/docker/postgrest.conf.

**Comment by steve-chavez** [comment]
Considering this resolved.
