### ISSUE TITLE
Ordering is broken (syntax error)

### ISSUE THREAD

**Issue by naehrstoff** [begriffs/postgrest#119]
It seems that specifying a sort order is broken somehow, all I get is a response mentioning a syntax error.

I tried this query: https://postgrest.herokuapp.com/speakers?order=name.asc

And get this result (in Postman 1.0.3 on OS X):

```json
{
  "status": "Fatal error",
  "hint": null,
  "code": "42601",
  "message": "syntax error at or near \")"
}
```

I started the server with `postgrest-0.2.4.9 -d pgapitest -U myuser -a myuser`.

**Comment by begriffs** [comment]
Oops, I see what you mean. My test cases only cover ordering when it's accompanied with another filter condition, but looks like it doesn't work right all by itself. https://github.com/begriffs/postgrest/blob/master/test/Feature/QuerySpec.hs#L26-L40

I'll fix this today, thanks for the bug report.

**Comment by naehrstoff** [comment]
Thanks for fixing this so quickly! I hoped I could learn a tiny bit of Haskell by looking at the fix, but oh no, I have no idea why it works now … I guess I'll have to be patient and study a bit more until I see it :smile:

**Comment by begriffs** [comment]
Yeah that's one drawback of picking Haskell for the project. It's kind of esoteric and makes it harder for people to jump in and contribute.

The bug was actually kind of a dumb mistake due to changing code. It's in a function that transforms a query to add a where clause if params are present. However the order param is special and does not affect the where clause. The transforming function should be (and now is) referring to the `cols` variable [[1](https://github.com/begriffs/postgrest/blob/4c74e54ae17a730dbdb51e17c6ec22eabf09f191/src/PgQuery.hs#L50)] which is basically all `params` except the order by one.

**Comment by naehrstoff** [comment]
I find the use of Haskell in this kind of project exciting: because it's a binary I can start using it without any barrier of entry, but then I still hope to one day hack a bit on it if it proves useful in our daily work – it basically gives me access to a Haskell code base that works in production at a time when I could not write something like this by myself at all.

Picking up my copy of LYAHFGG now and will keep a reference to this bugfix for when I know more about it :)
