### ISSUE TITLE
How it works

### ISSUE THREAD

**Issue by arunr307** [begriffs/postgrest#120]
hai,
can you please tell me how this works. Is it need to deploy in server?

**Comment by begriffs** [comment]
Hello! Yes, you have to deploy this to a server, although you can run it on your development machine as well to try it. Here is a good [article](https://cocoacoderly.wordpress.com/2015/01/04/postgrest-a-haskell-api/) someone wrote about getting started.

I will soon add a button to the readme which allows you to deploy to Heroku with one click, so that will make things easier.

**Comment by arunr307** [comment]
Can you explain the steps for running it on development machine with a sample rest api for create database.

**Comment by begriffs** [comment]
Do you have an existing database which you would like to turn into an API? If so, connect to this database, and add a schema named `1`. Then add views which expose the tables inside the public schema of your database. Then start postgrest with command-line arguments specifying the server, database name, port, username and password.

**Comment by begriffs** [comment]
I'm going to close this issue. Feel free to reopen if you have more questions.
