### ISSUE TITLE
support for pattern matching

### ISSUE THREAD

**Issue by rall** [begriffs/postgrest#132]
It would be handy if postgrest mapped one of its filters to LIKE queries. Is that likely to be supported in the future?

**Comment by begriffs** [comment]
Sure, this sounds like a valuable feature that probably won't be too much work to implement. Here's an idea for how the API could look: ```/items?foo=like.*hi*``` for case-sensitive LIKE queries and ```/items?foo=ilike.*Hi*``` for insensitive. I would have used percents rather than asterisks but percents have to be urlencoded weirdly. Does this look good to you?

**Comment by rall** [comment]
That would be perfect!
