### ISSUE TITLE
Is it possible to serve an entire single-page application (SPA) from PostgREST alone?

### ISSUE THREAD

**Issue by StefanScott** [begriffs/postgrest#136]
Hi - 

I understand that nearly all the browser requests in a single-page application (SPA) are to the REST API - except for serving the "main" page `index.html`, and an error page eg `404.html` - plus a bunch of `.js` and `.css` files - all of which are "static" assets/resources.

This makes me wonder: would it be possible to serve an *entire* single-page application (SPA) using PostgREST *alone* (ie, no other server)?

If so, could this be done by using the PostgREST *binary* "as-is" - or would it be necessary to go into the *source* to define how to handle a few additional routes (in WARP?) - eg:
```
"/"             GET  =>  index.html
".*/.+\.js"     GET  =>  /js
".*/.+\.css"    GET  =>  /css
_               GET  =>  404.html
```
I'm just using a quick-and-dirty make-believe route-matching pseudocode syntax above - similar to pattern-matching in Haskell or in an nginx.conf file (since I can't recall the correct syntax for such things off the top of my head at the moment :-) - just to get an idea of how few routes it would be necessary to define, for the limited number of static files which would need to be served in a single-page application (SPA).

**Comment by begriffs** [comment]
The routing could actually be simpler, you could define a directory (or s3 bucket) wherein all assets are considered static and served by their names. As far as I can see there are three reasons against doing this, and two reasons for it.

In favor:
* Fewer servers/services. All requests happen through one place.
* Ability for javascript code to access a same-domain api in old browsers that don't support CORS

Against:
* It complicates deployment. Currently updating your app means just changing your database. No changes are needed to the postgrest server. Adding front-end asset management to postgrest means you have to redeploy postgrest itself to get changes.  Although this may not be true if resources are in an s3 bucket.
* A slower user experience. The beauty of static assets is that they can be served from fast minimal servers like a content delivery network. Asking a specialized server like postgrest to handle those kind of requests might not be efficient. Now I realize with the right cache headers we can wrap a reverse proxy around postgrest and then future requests for assets might not even have to hit postgrest. But we could upload the assets to github pages or a CDN directly and skip the fuss.
* There are more standard ways. Even if you want to use the same machine for assets and api you can use common technology like nginx to conditionally route to postgrest rather than adding more logic to what is currently a pretty focused tool.

So my inclination is not to add this feature. Are there any reasons in favor that I overlooked?

**Comment by StefanScott** [comment]
Thank you for this clear and practical explanation of the pros and cons.

Now I see that it makes sense to let PostgREST focus on providing the REST API - and let nginx or a CDN serve the static assets.
