### ISSUE TITLE
Sorting looks broken

### ISSUE THREAD

**Issue by brikou** [begriffs/postgrest#147]
It looks like the sorting behaviour is broken. Check yourself https://postgrest.herokuapp.com/speakers?order=name 

Anyway is it possible to download an old (working) version of postgrest ? (or even build it)

BTW thank you for sharing this great project. Very good idea and implementation!

**Comment by begriffs** [comment]
This was addressed in https://github.com/begriffs/postgrest/pull/138 but has not yet made it into a versioned release. I'll be releasing a new version in the next day or so and will update the demo server.

You can actually make the current version work, but you have to do `/foo?order=asc.col` rather than `/foo?order=col.asc`.

**Comment by brikou** [comment]
Thanks, I'll update my code

**Comment by begriffs** [comment]
I have released version 0.2.6.0 that puts things in the same order as found in the documentation. I also updated the the demo app at https://postgrest.herokuapp.com/
