### ISSUE TITLE
using aggregate function 

### ISSUE THREAD

**Issue by arunr307** [begriffs/postgrest#167]
i need to use aggregate functions such as sum, count etc in my query.
example:
select address,count(id) from tbl_one where name='x' group by address;
for this i create a view 
create view test_view as select address,count(id) from tbl_one group by address;
but i can able to call API as localhost:3000/test_view?name=eq.x
if i add name in select field for the view my result for that query will change because of the group by condition that it follows.
how can i able to solve this.

**Comment by begriffs** [comment]
So the issue is that the WHERE clause is happening outside of GROUP BY instead of inside it? This does seem like a problem and maybe the only solutions is to allow calling stored procedures as described in  #114.

I've been trying to avoid allowing stored procedures because I worry that people will abuse the to create non-RESTful APIs.

**Comment by begriffs** [comment]
Postgrest now supports calling stored procedures: http://postgrest.com/api/reading/#stored-procedures

**Comment by Sigura** [comment]
of course it possible to make it as rpc, but hard to support two way for realisation features like responsible filters (slidebar with range between min-max values of shown rows)

just as suggestion for one of future releases:

query:
?select=min{rate},max{rate}&status=in.open,final

response:
```
{ min_rate: 1, max_rate:20 }
```

**Comment by Sigura** [comment]
guys, you are doing great job!

))) I really thought you did it ,))))
