### ISSUE TITLE
PUT request 405 with ajax

### ISSUE THREAD

**Issue by zukeru** [begriffs/postgrest#180]
I'm trying to do the following put request but my postgrest is returning a 405:

			function updateRead(id) {
				console.log(id);
				var d = new Date();
				var time = d.getTime();
				var post = { "read": "yes"};
				$.ajax({
					headers: { 
						'Accept' : "application/10.0.0.6:3000+json; version=1",
						'Cache-Control': 'no-cache'
					},
					url: 'http://10.0.0.6:3000/page_contact?id=eq.' + id ,
					dataType: 'json',
					type: 'put',
					contentType: 'application/json',
					data: JSON.stringify( post ),
					processData: false
				});
			}

**Comment by zukeru** [comment]
close this one figured it out.

**Comment by begriffs** [comment]
Can you explain what was wrong and what you fixed in case somebody else has a similar problem?

Also I notice you're using content type `application/10.0.0.6:3000+json` and I wanted to point out that you don't have to use your server address (10.0.0.6:3000) in there. The format `application/foo+json` just gives you the possibility to identify your own api with a name foo. If you like you can send `application/json; version=1`. No big deal, just FYI.
