### ISSUE TITLE
Filter by array column

### ISSUE THREAD

**Issue by RobinBressan** [begriffs/postgrest#181]
Hello,

Is it currently possible to filter results based on an array column? 
I mean if a `tags` column for example contains [tag1, tag2, tag3], can I filter all results having the tag3 value into the array?

Thanks

**Comment by begriffs** [comment]
That feature is not yet possible (unless you make a view that does it, and then access the view from the client side.)

What url syntax would you propose to do the array matching?

**Comment by RobinBressan** [comment]
Thanks for your answer.

What about `/collections?tags[]=eq.tag1&tags[]=eq.tag2`? Not sure about the `eq` part. 
We should then, receive the rows which have at least `tag1` and `tag2` into the `tags` column.

What do you think?

**Comment by edofic** [comment]
How about adding a new operator? 

    /collections?tags=contains.tag1&tags=contains.tag2

Or maybe

    /collections?tags=eq_any.tag1&tags=eq_any.tag2

Because this is closer to the `"tag1" = any(tags)` sql


@begriffs Is there a way to make a view for an arbitrarily big query/data? You could split up the array into columns but this puts the limit on the number of entries. Or maybe sort the array and concatenate it into a string and use `like` to query. But this requires escaping.

**Comment by edofic** [comment]
Giving this more thought I now prefer the extended column syntax that @RobinBressan proposed. 
I [implemented a variation of this on my fork](https://github.com/begriffs/postgrest/compare/begriffs:master...edofic:feature/array-filters). I added syntax for `all` and for `any` with support for the existing operators so no other syntax changes are needed.

`/entries?tags[any]=eq.Comedy` -> `where 'Comedy' = any(tags)`
`/entries?tags[all]=neq.Comedy` -> `where 'Comedy' != all(tags)`

I haven't opened a PR yet since I want to clean up my code a bit and add tests for the new extensions. Please give me some feedback so I know weather to invest time into it.

**Comment by diogob** [comment]
My two cents are that it would be better to keep the convention ```column=operator.value```.
In this case something like ```/entries?tags=contains.Comedy``` or ```/entries?tags=notcontains.Comedy```

**Comment by edofic** [comment]
@diogob That would mean you cannot do something like `/entries?ratings[all]=geq.4` or at least you would need separate operators. 
We already have JSON columns which "break" the convention `/stuff?json_col->a->>b=eq.2`

**Comment by ekosz** [comment]
Has there been anymore updates on this? Is there a way of querying for a value in an array column using postgrest right now?

**Comment by ruslantalpa** [comment]
No updates, we've been busy rewriting most of the code but this feature would probably be easy to implement. When the new version is ready, this will also be included

**Comment by begriffs** [comment]
@edofic your work on the fork is pretty cool. Would you still be interested in leading our efforts to bring this issue to a conclusion?

**Comment by ruslantalpa** [comment]
I think the availability of `<@ and @>` operators this can be expressed like this
`tags=@>.{tag1}`
which generates something like 
```SQL
select ARRAY['tag1','tag2'] @> '{tag1}'::unknown
```

**Comment by edofic** [comment]
@begriffs sorry for the late reply - I somehow missed this. But yes, I can take this over.

**Comment by ruslantalpa** [comment]
@edofic is there any point to extendibg the syntax when the original question can be answered using features already present?

**Comment by edofic** [comment]
@ruslantalpa I was not aware this is already implemented because I didn't see it in the docs. Tried out your example and I'm quite happy. I opened #626 to update the docs. I think this issue can be closed now.
