### ISSUE TITLE
PATCHing transactionally

### ISSUE THREAD

**Issue by parauchf** [begriffs/postgrest#208]
The current implementation of PATCH is I think not completely in line with standards.  Specifically from RFC5789:

> The PATCH method requests that a set of changes described in the request entity be applied to the resource identified by the Request-URI.  The set of changes is represented in a format called a "patch document"

RFC6902 specifies a format for JSON patch files.  They look like this:

``` 
[
     { "op": "test", "path": "/a/b/c", "value": "foo" },
     { "op": "remove", "path": "/a/b/c" },
     { "op": "add", "path": "/a/b/c", "value": [ "foo", "bar" ] },
     { "op": "replace", "path": "/a/b/c", "value": 42 },
     { "op": "move", "from": "/a/b/c", "path": "/a/b/d" },
     { "op": "copy", "from": "/a/b/d", "path": "/a/b/e" }
]
```

I'm not a REST fundamentalist, and honestly think these "patch documents" are excessively verbose, but the current implementation is maybe not future-proof.  Thoughts?

**Comment by begriffs** [comment]
Actually the patch verb is agnostic with respect to the patch format used. So I opted to use a simpler format. :smile: From the RFC:

>it is expected that different patch document formats will be
   appropriate for different types of resources and that no single
   format will be appropriate for all types of resources.  Therefore,
   there is no single default patch document format that implementations
   are required to support.  Servers MUST ensure that a received patch
   document is appropriate for the type of resource identified by the
   Request-URI

You're right that we should be clearer about what's going on though. We should think of a name for the patch document format used in PostgREST and put it into an [Accept-Patch](https://tools.ietf.org/html/rfc5789#section-3.1) header.

Another issue is whether to also support the full `application/json-patch+json` format. Does it provide features that you would like to use?

**Comment by parauchf** [comment]
Actually no, I don't have any use for `application/json-patch+json`!  I was pleasantly surprised by the simplicity of the PATCH method you built in--it's the kind of method I've always built and felt guilty about.  Thanks for the response!

**Comment by motiz88** [comment]
I was just going to try and start a discussion about this, myself. I see a lot of value in RFC 6902. My own use case involves syncing a relatively "fat" client-side store with PostgREST in the face of optimistic updates, undo/redo, network outages, constraint checking, back-end processes potentially updating the DB, and (to a lesser degree) multi-user access. Therefore my Flux+React frontend already manages its core data mutations as JSON patches on top of immutable data structures, and naturally I would love to use those same patches when communicating with the server. It would provide the client with greater insight into the state of the DB after each update.

More generally, I think the nicest feature of JSON patches that PostgREST may be missing is their transactional nature. They are in fact a way to write potentially complex transactions applying to a single table/view using a small set of primitives. I humbly submit that there's a place for that capability in PostgREST, and that it might as well be an RFC 6902 implementation since that's standard, well-understood and (at the very least) gaining acceptance.

**Comment by begriffs** [comment]
Good point about being able to encode some types of transactions in an already documented format and about the operations lining up nicely with immutable data structures on the client. They seem like good reasons to support rfc6902.

**Comment by jmealo** [comment]
@motiz88: :+1: I have similar reasoning.

**Comment by begriffs** [comment]
Batching requests into a transaction is very important. I don't think we need the special patch format to do it though. What I have in mind is supporting HTTP/2 with the convention that if multiple requests come into a single HTTP/2 connection then they will be put into the same sql transaction. Seems more general purpose.

Thoughts?

**Comment by bastih** [comment]
What about non-http/2 clients?

**Comment by jmealo** [comment]
@begriffs I believe that the http/2 connection will stay open basically indefinitely when used with websockets or any kind of periodic polling, even playing a video/audio stream from the same server, so I'm not sure if that would work. I'm not sure if multiplexing still happens when the connection has been upgraded to a websocket connection. I do know if socket.io is using XHR polling with a ping/pong behind NGINX that the connection will stay open. If you have your websocket server and postgrest behind the same front end I don't see how you can use the duration of the HTTP/2 connection for transactions.

**Comment by begriffs** [comment]
Whether or not the solution involves HTTP/2, it seems like this particular issue is an instance of batching requests into a transaction. Let's move conversation over to #286.
