### ISSUE TITLE
"resource" routes based on primary keys?

### ISSUE THREAD

**Issue by drawks** [begriffs/postgrest#235]
I just found postgrest yesterday and it looks really awesome. However I was bummed to find this line in the documentation:

> Every view and table accessible by the active db role is exposed in a one-level deep route.
> There are no `deeply/nested/routes`.

While I understand that simplicity of generalized solutions has to be held as critical. It seems like not having direct resource routes throws out a pretty fundamental design principle of REST in that endpoints can be either resources or collections of resources.
The existing postgrest api seems to only address routing for collection endpoints. Which means:

* The header portion of the api response must always be scoped to a collection 
 - #234 - link headers for expressing foreign relationships, can't exist in collection scope
 - link headers expressing relationships to other objects in the same table can't exist in collection scope. I.E. can't have prev/next links to allow for treatment of objects as nodes in a linked list.
* Interactions with the API from a developer standpoint must always guard against a collection of greater than one resource even when constructing queries designed to return a single resource.

#116 asked for a similar feature but was shot down on the complexity of providing a general solution in light of things like compound primary keys and un-serializable primary key types. However I think that there are at least two relatively simple paths forward.
1. Provide canonical resource endpoint only for tables that meet a minimum schematic requirement. I.E. non compound primary key of a simple scalar (str, int, float) type.
2. Same as above but, in addition... Identify primary keys that don't conform to the strict requirements of above and provide the endpoint URI based on a hash of the key that can be represented easily in a URI

Thanks in advance for your time in reading/responding to this issue and also to everyone who has contributed to this project.

**Comment by Jefffrey** [comment]
Do you mean links like `/foo/1` as opposed to `/foo?id=eq.1`? If so, what do they add as a functionality? Why should they be considered? Don't they just add complexity as they introduce a special rule for which these "pretty links" can be used?

**Comment by drawks** [comment]
I think I outlined pretty well some of the advantages of having single resource endpoints. The primary thing is just having canonical URIs for any given resource. Right now everything is referenced in terms of a collection. As for the added complexity, it seems like it would pretty minimal while at the same time providing for more natural entry points for things like representing foreign relationships.

**Comment by drawks** [comment]
It seems like @mgomezch is making some solid arguments against using link headers in #235 but replace the concern about link headers with etag or modified headers and once again having a canonical single resource URI would allow for quick smart introspection of the state of an resource which makes a bit less sense in the case of an arbitrary collection of resources.

**Comment by mgomezch** [comment]
It could be argued that relational theory itself doesn’t actually provide any operators in its algebra that single out a specific resource.  Indeed, SQL doesn’t have any sort of `GET THIS ONE SPECIFIC ROW` statement that fetches some unique thing — it has a `SELECT` statement that **always** produces collections.  They may just happen to be singleton collections, and this is guaranteed if you match a set of columns by equality that has a uniqueness constraint, and there happens to be a match.

In Haskell terms, `SELECT :: stuff → [Row]` — maybe an empty list, maybe a singleton list, but always unavoidably a list.  If PostgREST resources match SQL `SELECT` operations, then it’s sensible that there are only collective resources, and none individual.  We just happen to simulate individuality with constrained tables a lot and it’s kind of crucial for most systems employing RDBMSs.  In that sense, the current PostgREST philosophy is very much correct and follows relational theory canon — it’s just that most people assume primary keys will always be around in order to do anything useful.

My take on this is that guaranteed singleton-or-empty (as in `Maybe`) resources correspond to each `UNIQUE` constraint in a Postgres database — *not* to each table.  Perhaps `UNIQUE` constraints should get their own resources?  How would this look in practice?

**Comment by drawks** [comment]
I can see that SQL's select doesn't have non-collection semantics. However I don't think it is any sort of logical stretch to imagine a representation of a single row object selected by it's primary key. It is a very common access pattern in ORM libraries to operate on single objects that are mapped to a row on only the primary key. If the goal of this project is to simply "rest-ify" SQL then I buy your argument against having single resource endpoints, but I'd argue that if your goal is to satisfy the desire to have a truly restful api that happens to be backed by postgresql and driven by DB schema design then there is plenty of room for supporting these single resource endpoints and that their inclusion would make your project more natural to use for consumers who don't happen to care that the rest layer is presentation of an SQL backing store.

The question as to whether all UNIQUE constraints should be represented this way seems academic since at the point the point you extend the idea beyond primary key, something which by definition there can be only one of in a table, the requester would be back to having to refer to the column name and the existing collection end point with query args to stand in for filtering is plenty expressive to that end. Unless I've misunderstood your final paragraph.

**Comment by begriffs** [comment]
Some thoughts about this excellent discussion

### Singular resources

The app is able to tell if the filtered columns comprise a primary key (there is an example [here](https://github.com/begriffs/postgrest/blob/master/src/PostgREST/App.hs#L170)). The client could send a `Prefer` header to indicate whether the response in this case should be an object or a singleton array, with the array being the default. When the object format is requested but no rows match the key constraints then the server would return 404 rather than 200 with an empty array. If an array response contains exactly one element we could include Link headers if applicable, same as if the object format is requested.

### Caching concerns

I think if we decide how to generate etags for a single row then we can imagine a way to combine them into an etag representing the state of a collection of rows. Also modification headers can be combined (e.g. Last-Modified is the latest of any in the collection, Expires is the earliest).

### Next- and prev-links

It seems the use of [range headers](https://github.com/begriffs/postgrest/wiki/Routing#limiting) for navigating results is strictly more expressive than linked-list-style pagination headers. Or am I misunderstanding you, @drawks?

### /foo/1 vs /foo?bar=eq.1

The former is a degenerate case for simple (and overwhelmingly numeric) primary keys. It is feasible to detect when we are dealing with a table of this form and allow `/foo/1` while providing a `Link: </foo?bar=eq.1>; rel="canonical"` header in the response.

**Comment by begriffs** [comment]
This issue is not well enough focused so I'm closing it. We can open individual issues each for singular resources and simple numeric primary key url sugar.
