### ISSUE TITLE
Password is visible on a ps listing

### ISSUE THREAD

**Issue by gmiddleton** [begriffs/postgrest#277]
To recreate:

1) Start postgrest
2) Run ps -ef on the machine
- The password is visible in the listing

Can the option to specify a config file be added?

**Comment by PierreR** [comment]
In case it helps, I am using socket and an pg_hba rule to allow local trust connection to the specific user/database. With that scenario I don't need to pass the password around.

**Comment by begriffs** [comment]
We could add support for a config file. You might also set an environment variable like `PG_PASS=foo` then launch the app with `--db-pass=$PG_PASS`.

**Comment by jmealo** [comment]
@begriffs if we're using ``libpq`` this would be best practices to keep the credentials out os ``ps``, config files and version control:
http://www.postgresql.org/docs/9.4/static/libpq-pgpass.html
http://www.postgresql.org/docs/9.4/static/libpq-pgservice.html

In the long run I think that we'll want a configuration file, however, postgrest is a good chance to teach people good practices and I believe that ``pgpass`` and ``pgservice`` aren't well known. Since most client libraries are based on ``libpq`` this is good for polyglot stacks as well.

**Comment by PierreR** [comment]
I am not using a .pgpass file for now (will do if I need more security) but I would expect it to work with `postgrest`. It doesn't ?

**Comment by jmealo** [comment]
@PierreR I checked the dependency chain and it looks like the haskell library supporting the binary PostgreSQL protocol uses ``libpq``, but it's hard to tell if hasql would use it for authentication. I'm not sure where the separation of concerns is there, I'm sure @begriffs will know.

**Comment by begriffs** [comment]
@PierreR did the `.pgpass` thing end up working?

**Comment by PierreR** [comment]
I haven't tried yet because I am happy with my current setting (socket and a pg_hba rule to allow local access). Maybe @gmiddleton would give it a go ?

**Comment by joncfoo** [comment]
I just tried using pgpass and it works (with 0.2.12.0).  The resulting command was simplified to ./postgrest-0.2.12.0 -d mydb -U myuser -a anon --jwt-secret mysecret
