### ISSUE TITLE
Better documentation with regards to authentication

### ISSUE THREAD

**Issue by Jefffrey** [begriffs/postgrest#313]
I've read "Security and Permissions" (https://github.com/begriffs/postgrest/wiki/Security-and-Permissions) and I'm left with a lot of questions:

 1. How do I create the "authenticator" role?
 2. How do I create an admin-like user within the database? (The documentation says that we should be using `/postgrest/users` to create a new user, but what if I don't want the outside world to be able to create a new user?)
 3. Are the attribute names in the given `postgrest.auth` example required to be those or can I customize them?
 4. Has the authentication table have to be in `postgrest`'s schema?
 5. What does the line `SET search_path = postgrest, pg_catalog;` actually do? What's `pg_catalog`?

**Comment by Jefffrey** [comment]
The answers seem to be:

#Answer 1

You just run:

````
create role authenticator;
```

#Answer 2

As far as I can see you have to run:

```
grant usage on schema postgrest to <anonymous role>;
grant insert on postgrest.auth to <anonymous role>;
```

then submit the post request to create your first admin-like user. Then revoke them via:

```
revoke grant option for insert on postgrest.auth from <anonymous role>;
revoke grant option for usage on schema postgrest from <anonymous role>;
```

#Answer 3 & 4

You cannot customize them as of right now. They [seem to be](https://github.com/begriffs/postgrest/blob/master/src/PostgREST/Auth.hs#L79) hardcoded. Same is true for the `postgrest` schema.

**Comment by diogob** [comment]
@Jefffrey this is a hot topic now, and the authentication system is being overhauled. You can take a look on what is being discussed here #260 and here #311

**Comment by calebmer** [comment]
The docs are [also being overhauled](http://postgrest.com) so hopefully we can preemptively answer questions like these in the future 😊

The answer to 5 confused me at first too, but it seems to be just like changing your `PATH` variable on a unix machine. The following statements select the same thing:

```sql
SELECT * FROM postgrest.auth;
```

```sql
SET search_path = postgrest, pg_catalog;
SELECT * FROM auth;
```

I'd also like to ask you a couple question @Jefffrey, one of the breaking changes in our new auth API is that there is no auth API…

This allows developers to be more flexible and enables them to roll out custom solutions for their unique scenario. What do you think about this change (1)? Also some contributors are postulating creating a PostgREST add-on which adds an auth API back in for developers who want it. How would you feel about a second project which bakes in an auth API (2)?

**Comment by begriffs** [comment]
To elaborate, version 0.3 has removed the basic auth and accepts only [JWT](http://jwt.io/) which specify the database role to use to carry out a request. The idea is that other programs or services can generate these tokens and postgrest doesn't have to reimplement auth flows.

For instance I discovered https://auth0.com last night, and I'm working with their engineers to generate postgrest-compatible JWT. When I figure it out I'll add the procedure to our docs. This service can translate logins from Twitter, Github, etc into the API tokens we need.

**Comment by Jefffrey** [comment]
@calebmer Sounds good. The existing auth flow was hard coded and not very flexible.
I'm not particularly versed in OAuth and OpenID/OpenID Connect, so I don't know how that would translate into, but I'm curious to see the alternatives now and how a full implementation would work.

**Comment by begriffs** [comment]
@Jefffrey could you review these new docs and let me know if they're still unclear?

* http://postgrest.com/examples/users/
* http://postgrest.com/examples/blog/

**Comment by NikolayS** [comment]
Things that seem to be unclear:  
 - while many projects either (a) already have `users` table or (b) are developed to work with millions of users, it's unclear how to design auth functions/triggers/tables. http://postgrest.com/examples/users/ is dealing with Postgres roles, the way that suit to not so many projects ("Good old issue #260")
 - for a project that cannot deal with Postgres roles ("role per user" approach) it's unclear how to implement row-level security:
  - how to insert user id automatically during INSERTs of some content (blog is a good example, especially if considered with multi-million user base)
  - even with "role per user", it's unclear how use it in Postgres 9.4. There is a way to emulate row-level security in 9.4 (http://blog.2ndquadrant.com/emulating-row-security-in-postgresql-9-4/), but it relies on security_barrier and can lead to performance issues in case of many rows in the table ("Views created with the security_barrier may perform far worse than views created without this option." – see http://www.postgresql.org/docs/9.4/static/rules-privileges.html)
 - http://postgrest.com/examples/blog/ mentions `basic_auth.current_email()`, but I cannot find definition of it anywhere

**Comment by calebmer** [comment]
I'm doing auth without one-role-per-user for the moment because I agree @NikolayS, until it's been proven I'm not confident with using it 😊

Here's what I do, in all my JWTs I have an `agent_id` field which is an integer and the `person` role. `agent_id` can be received in Postgres with `current_setting('postgrest.claims.agent_id')` (that value is a string so I put it in a function to cast it to an integer). This works well with RLS as I know when the role is `person`, `agent_id` must be defined.

I can try to document this approach, but I don't have much time to do so therefore it might not happen for a bit.

**Comment by NikolayS** [comment]
@calebmer thanks for explaination, I already doing the same (using `postgrest.claims.*` vars in my plpgsql functions -- I took a while to figure out it w/o docs, github search helped). 
And since I have Postgres 9.4, I don't use RLS. Instead, I just overwrite row's owner ID in the trigger, using info from`postgrest.claims.*`. Plus, in case of UPDATEs, trigger checks that `NEW.ownerID = OLD.ownerID` (if not, it raises an exception).

**Comment by diogob** [comment]
I'm using Rails+Devise for user management and 1:N role to users. I could document this approach and add the the examples section. Do you guys think that would be helpful?
Concrete examples with existing frameworks might be an excellent way to show how to use JWT.

**Comment by calebmer** [comment]
That would be great, but could you possibly abstract away the rails stuff? I'm afraid everyone will want their own specific framework tutorial after that.

**Comment by diogob** [comment]
@calebmer yes I can. But I don't see any problem in having several different examples of integrations, having very concrete material is good for newcomers. I promise I won't copy ruby code though :P

BTW, there are several examples (a bit outdated) of auth and use of claims in this repo: https://github.com/diogob/postgrest-benchmark

Maybe we this can be useful if formatted to fit the docs properly. @NikolayS and @calebmer could you take a look at this repo and check if there is anything that might be of value?

**Comment by begriffs** [comment]
@NikolayS 

* To migrate users from an existing system to the new auth table you could update the [user_role](https://github.com/begriffs/postgrest/blob/master/schema-templates/blog.sql#L138-L149) and [login](https://github.com/begriffs/postgrest/blob/master/schema-templates/blog.sql#L234-L251) functions from the blog template. You would have `user_role` consult the legacy auth table to check if the user logged in correctly. If the login is legit then have `login` create a new entry in the postgrest specific auth table since the `login` function has their email and plaintext password at this point and is able to create the row. Thus the users migrate to the new system one by one as they log in.
* To share a role between multiple users yet maintain per-user permissions you can add filter conditions to views which check `current_setting('postgrest.claims.email')`. Triggers can check it to as needed.

@diogob I'd love your help documenting the Rails+Devise stuff.

**Comment by MikeSchroll** [comment]
@begriffs any progress on integration, working with auth0 engineers?

**Comment by begriffs** [comment]
@MikeSchroll sorry I haven't looked into it.

**Comment by Jefffrey** [comment]
The documentation looks clearer.
