### ISSUE TITLE
Reducing ambiguity in query parameters

### ISSUE THREAD

**Issue by calebmer** [begriffs/postgrest#354]
Say I have a post object which looks like this:

```json
{
  "id": 5,
  "headline": "Hello, world!",
  "author": 2,
  "editor": 7
}
```

Where both `author` and `editor ` link to a row in the `person` table.

The current `select` parameter does not allow us to expand both (one would try something like: `?select=person(*)`). How should we resolve this issue?

I propose we allow for the following: `?select=author(*),editor(*)` and that expands the `author` and `editor` fields respectively. Thus above would become:

```json
{
  "id": 5,
  "headline": "Hello, world!",
  "author": {
    "id": 2,
    "name": "Jen"
  },
  "editor": {
    "id": 7,
    "name": "Sam"
  }
}
```

One scary part of this, however, is that in one request `author` and `editor` return a number, and in the other `author` and `editor` return objects (personally, I don't see this as too big an issue, but it must be considered nonetheless). One solution to this problem is using JSON-LD (#343) where `author` and `editor` always return an object with an `@id` field.

**Comment by ruslantalpa** [comment]
There is a bit of cheating going on here :) usually those fields will be called author_id and editor_id and what you will get back is author_id: {...}, editor_id:{....} and that does not look good. If you decide to name them as in the example above then author: 10 or editor: 20 also does not look right.
Is this author/editor example common, can anyone provide a real situation that he encountered such a thing?
another way would be something like
&select=id,name,author_id@users(*) or some other syntax/way.

**Comment by calebmer** [comment]
With #353 `author` and `editor` is not cheating, it's a good design 😊

Also, whatever solution we decide, we should keep nested routes in mind. `/person/1/author_id@users` looks a little cumbersome there.

**Comment by begriffs** [comment]
Suppose a blog `post` table has columns `author_id` and `editor_id` which are integers and foreign keys both referring to the `users` table. They might have been named anything really, could have been named `author` and `editor` and postgresql doesn't care. What matters is the the foreign key constraint.

I think it's important to reveal the actual column values for reading and writing. It's also important to allow embedding in the API. Whatever the columns are named I'd like to preserve those names in the output along with their true values. This way if you PATCH the endpoint you will be writing the same types of values to the same columns as when you GET from the endpoint.

I'd advise we don't change the type of `author_id` (or `author` depending how it's named) to sometimes by an integer and other times be a nested object. Here's an idea, if the user requests

```http
/posts?id=eq.5&select=*,author_id(*)
```

Then respond

```json
[{
  "id": 5,
  "headline": "Hello, world!",
  "author_id": 2,
  "editor_id": 7,
  "_embed": {
    "author_id": {
      "id": 2,
      "name": "Jen"
    }
  }
}]
```

This leaves the original column intact, and adds the `_embed` object whose keys match the names of the foreign key columns.

**Comment by calebmer** [comment]
@begriffs with the thinking that every column should maintain its same name, are you against the current `?select` functionality which embeds a `users` object? (key is table name vs. column name)

Also, I'm not the biggest fan of that solution. I feel as if JSON-LD is a more elegant/canonical solution. Do you have any opposition to JSON-LD?

**Comment by diogob** [comment]
Just please, let's keep away from nested routes :D

**Comment by ruslantalpa** [comment]
The proposed solutions are
@calebmer 
Have the api dev (db admin) name the columns like this
```
{
  "id": 5,
  "headline": "Hello, world!",
  "author": 2,
  "editor": 7
}
```
and the frontend dev will request data like this
```
/posts?select=id,headline,author(*),editor(*)
```
pros: select parameter looks nice and short
cons: you either have the ambiguity of what select=author(*) vs select=author means or you only can get the author as an embeded object without the posibility of getting just the id.
This also goes against "point postgrest at any db and it will give you an api"

@ruslantala
The table structure is more likely to look like
```
{
  "id": 5,
  "headline": "Hello, world!",
  "author_id": 2,
  "editor_id": 7
}
```

and this is how you would request the data
a) requesting children
```
/projects?select=id,name,tasks(*)
```
b) requesting parents (when the table contains a single fk pointing to a specific foreign tables)
```
/projects?select=id,name,client:clients(*)
#meaning get me the related data from "clients" but rename the nodes to "client" because i know it's  a single object
```
c) requesting parents (when there are two fk pointing to the same table, the example from which the discussion started)
```
/posts?select=id,headline,author:persons[author_id](*),editor:persons[editor_id](*)
#meaning get me the related data from persons table, rename the node to author/editor and use the foreign key called author_id/editor_id
```

cons: the select parameter syntax is longer (but i say it's longer when there is underlying complexity)
pros: i can get the response body exactly in the format i want (just the fk id or embed the object if i need). 
frontend and backend dev do not have to agree before hand on how to name the fk columns in order for the response body to look in a certain way.
the backend dev can chose the style of the names used for fk like "author_id" or "author_fk" without affecting the shape/names of the response body.


In my view i think the goal is to give the frontend dev the possibility of shaping the response body exactly the way he wants at the expense of having a more complicated select parameter and without the need to have the backend dev do anything for that.
I think it's way less code to construct a complicated select parameter then the code needed to parse and transform the data that comes back because it is not in the shape the front end dev wants it to be.
An example.
the backend dev (db admin) likes his columns named "first_name", "last_name". the front end dev likes "firstName", "lastName".
With the functionality i described, the backend dev does not need to create a view in order to rename the columns, the frontend dev makes a request like so
```
/users?select=firstName:first_name,lastName:last_name
```

**Comment by diogob** [comment]
@ruslantalpa 's proposition seems more composite-key friendly. And it could be further improved using default aliases. For example, if I use:
```
/posts?select=id,headline,persons[author_id](*),persons[editor_id](*)
```
The response could be generated with: **person_by_author_id** and **person_by_editor_id**.

**Comment by calebmer** [comment]
I forgot about compound keys. @ruslantalpa how do you propose we select compound keys by column names with your method?

**Comment by ruslantalpa** [comment]
We have a joke here "you are on the bear's side" as in "you are playing the devils advocate" :)
I have no idea but i think it's a very "corner case".
What are the chances of having a table that references a foreign table two times using a compound key, i.e. having 4 columns which taken in pairs form 2 references.
i guess you could say
```
persons[key1,key2](*), persons[key3,key4](*)
```
so this situation is not a "con" for the @calebmer solution since i don't think it exists (99.99%). But now that you mentioned it, that solution indeed breaks down when the reference is done using a compound key (because you are using the name of the fk column and not the name of the referenced table)

**Comment by calebmer** [comment]
I have some new information on this issue.

For front end data retrieval with ReactJS my team has been experimenting with some GraphQL-like approaches. One that we are growing fond of is almost exactly like what Facebook pitched in their initial GraphQL presentation. It looks like this:

```js
select({
  id: null,
  headline: null,
  createdAt: null,
  author: {
    id: null,
    givenName: null,
    familyName: null
  },
  comments: [{
    id: null,
    text: null,
    author: {
      id: null,
      givenName: null,
      familyName: null
    }
  }]
})
```

(The array syntax is nothing but syntactic sugar) We like this a lot as JavaScript objects are highly composable, can be turned into a `propTypes` object, has the potential to embed extra data with the value, and it translates very nicely to the following PostgREST request:

```
?select=id,headline,createdAt,author(id,givenName,familyName),comments(id,text,author(id,givenName,familyName))
```

However, as we know, we can't currently select using `author(*)`. Currently we would have to switch out `author: {…}` with something like `people: {…}` which causes some cognitive dissonance as the key is plural, but the data is a single  object. With @ruslantalpa's recommendation `author: {…}` would be `"people[author]": {…}`.

**Comment by ruslantalpa** [comment]
The last part is not correct.
your request would be
author:people[author_id](*)
first part is the desired name in the response
second part is the table name
third part (when there is ambiguity in keys) is the key to use.

**Comment by calebmer** [comment]
My bad, but the syntax gets even more confusing for the above use case with keys that look like `"author:people:author_id": {…}`.

**Comment by calebmer** [comment]
Also, that solution doesn't solve the nested comments problem, where the `comments` table has a reference to itself at `parent_id`. What does `comments(*)` select? All child comments, or the parent comment?

**Comment by calebmer** [comment]
Here's my updated proposal.

We keep the current method of selecting embedded resources, but we add the column name method on top. So `parent_id(*)` or just `parent(*)`.

@ruslantalpa makes the good argument that there is no way for the developer to tell (at glance) that one selects from a column and the other from a table. I think this is an issue solved by convention. If database admins are using the popular convention of `*_id` it's not an issue. Another convention we could allow for is using parentheses (`parent(*)`) for one type, and brackets (`comments[*]`) for another. Which one would not matter to PostgREST, only to implementors.

To solve the other problem of data integrity (`parent_id` is sometimes a number, sometimes an object. I don't think this is a problem in 80% of cases), we could allow for aliasing. So `parent:parent_id(*)` could be allowed.

I feel like both proposals could be reasonably implemented in PostgREST and there usage, a matter of convention.

**Comment by calebmer** [comment]
Adressed in #424
