### ISSUE TITLE
Windows Compilation Fails with bcrypt error

### ISSUE THREAD

**Issue by pbel78** [begriffs/postgrest#395]
Hi

I have tried to compile postgrest for windows. version 0.2.12 as well the 0.3.0.1 fails with the bcrypt module:
[ 8 of 12] Compiling PostgREST.DbStructure ( src\PostgREST\DbStructure.hs, .stac
k-work\dist\d96ab9d9\build\PostgREST\DbStructure.o )
ghc.exe: unable to load package `bcrypt-0.0.7'

(version 0.2.12 fails with the same message but with bcrypt-0.0.6 . I have checked if bcrypt was downloaded.. it is. using the newest "stack" for windows as stated in the manual.

Postgres is installed on this Windows 8.1 machine (version 9.4) also installed are the odbc drivers.

Does anyone has an idea what the problem could be? Or what information migth help you to understand the problem on my machine?

Thanks
Regards
Petr

**Comment by begriffs** [comment]
A couple ideas.

1. What happens if you run `stack install bcrypt` by itself?
2. Does it help to build and install bcrypt from source first? http://download.openwall.net/pub/projects/crypt/

**Comment by begriffs** [comment]
I'm downloading a VirtualBox image for windows so I can try to reproduce. I'll start including windows binaries in the official releases once we figure this out.

**Comment by begriffs** [comment]
I've built you a windows x64 release! https://github.com/begriffs/postgrest/releases/tag/v0.3.0.1

I ran into the bcrypt problem too, but then I realized we don't use bcrypt anymore because we let postgresql do password encryption. So I removed bcrypt from the cabal file and it built fine. I'll apply that change to master so that future releases will build in windows. But I'll also include a pre-built windows binary in future releases.
