### ISSUE TITLE
Some Issues (regex-tdfa, Auth of JWT way)

### ISSUE THREAD

**Issue by uuhan** [begriffs/postgrest#401]
PostgREST is really a tasty cookie :) 

I recently used it in my own project, en, nicely performed. But I found some thing not convenient: 
Firstly: PostgREST relys on regex-tdfa, but I have installed regex-tdfa-rc in my system, so I have to change the .cabal file of PostgREST to satify my need.

Secondly: I dont quite like the JWT way to authenticate(not know well with jwt and it does to much work in PG server side in this way), I would like to use postgrest as a Swiss Knife to power my Yesod app, so I turned It into a WAI app ,  with 
Network.Wai.Middleware.Vhost(vhost), rewrite pathinfo of the request, and write a HttpDigestAuth module to perform the authentication. It works pretty well with my Yesod App.

So, Why not get rid of the JWT way , to forcus on the PostgREST's functions, and give the full authorization control to the users?

**Comment by begriffs** [comment]
Glad to hear it's helpful for your project. What project are you working on?

About your regex library question, are you able to have `regex-tdfa` and `regex-tdfa-rc` both installed  on your system at once? You could try Stack of cabal sandboxes. Also it looks like the `regex-tdfa-rc` is outdated, so maybe you want to switch away from it.

Now about JWT. it has two benefits:

1. External (non-Haskell) services can generate JWT on behalf of the PostgREST server. All these helpers need to know is a shared encryption secret. JWT is pretty flexible, able to integrate with systems like Auth0 who can hook up with still more [identity providers](https://auth0.com/docs/identityproviders) and generate JWT.
2. PostgREST uses information in the database to create an API. This includes database roles and their permissions. Rather than write custom authorization code in my web server to determine the information people can see, we use the database. When a client authenticates with JWT, PostgREST changes which database role it uses to execute commands. Using the database for permissions allows us to implement things like a username/password system in sql like [this example](http://postgrest.com/examples/users/).

If it is more convenient to you to do your own authorization in a middleware (or even nginx) then you're free to do that. The JWT support just enables other possibilities.

**Comment by calebmer** [comment]
There have been long debates about auth, for some context see what we call good ol' #260.

We went with JWT because it allows for *any* method, it is the ultimate in extensibility. The idea is we aren't in the authenticator business, we are the resource server (as defined by the OAuth2 spec) and developers role their own authentication server.

Currently I'm writing my own JWT based auth system in a node server which gives me the flexibility my app requires. However, I agree in that PostgREST should provide some authentication support. We claim to follow industry best practices, we should probably give that in the authentication field too. I assume you are a Haskell developer @uuhan, and you are an unbiased (at least in terms of the projects history) PostgREST user, so your recommendation on where to go for auth is very helpful. Here are the options as I see it:

1. Only JWT, nothing else.
2. JWT with some SQL templates showing an auth example with `/rpc` (we do this now).
3. JWT with a basic auth system built into core.
4. JWT with an advanced auth system built into core.
5. PostgREST + a new project (PostgrAUTH? Play on words doesn't work here 😊) which creates JWT tokens for a PostgREST system using Postgres.

I think most core devs want to take an approach similar to 5 (this also fulfills the REST layered system constraint) however very few have the motivation.

**Comment by uuhan** [comment]
@begriffs I turn PoetgREST into a module of my Yesod app which is a small Project manager, a small OA system for my group.

@calebmer En, I am a Haskell developer and really enjoy with It :) .. I think It's good to be more modularized for postgREST.  Like Yesod, I think it's really good idea to have a 'postgAuth' (similar to yesod-auth), to satisfy all the need of the users.

**Comment by begriffs** [comment]
We're going to keep JWT support for the time being. You don't have to use it and can provide your own auth with middleware if you like.

Can you tell me more about the `regex-tdfa` problem?

**Comment by begriffs** [comment]
I'm closing this issue because `regex-tdfa-rc` is deprecated in favor of `regex-tdfa`.
