### ISSUE TITLE
Relation to JSON API

### ISSUE THREAD

**Issue by maxnordlund** [begriffs/postgrest#437]
This is a pretty awesome project, but I'm curious if you have seen http://jsonapi.org/ at all?
It seams to be a good fit, and maybe will help to solve #343 and #310.

Basically it defines a transfer protocol for nested relations, and I think it's moving to adopt JSON-LD. This is supported by both client side and server side libraries, see http://jsonapi.org/implementations/ for more, to allow easy integration.

**Comment by calebmer** [comment]
I've looked at this before in the dark days (read: pre PostgREST). My general impression is JSON API is a more standardized, but less powerful [Falcor](http://netflix.github.io/falcor/).

I don't think it's a good choice for PostgREST. The way it expresses relations is a little verbose and can be much easier done with hypermedia (think JSON-LD). It also includes semantics which are much better delegated to HTTP headers like pagination and links.

It's my opinion that clients should enhance the PostgREST experience. Not dictate it. A client should not be required to easily work with data served by PostgREST. I prefer JSON-LD because it is a very unobtrusive addition addition to the JSON data format and gives most (if not all) of the caching power (combined with HTTP headers) which Falcor and JSON API provide.

* * *

That said, I do think a powerful extension of PostgREST could be allowing different data renderers. However, I'm not convinced that's a super important/wanted feature.

**Comment by batisteo** [comment]
EmberJS now supports out of the box the Json api. Any updates concerning your opinion?

**Comment by begriffs** [comment]
On one hand many clients probably support json-api, on the other postgrest supports openapi already (on the master branch and soon to be released in v0.4) to document api structure. I've created a todo for myself to carefully evaluate json-api.

**Comment by begriffs** [comment]
So I looked at json-api more. I can see how it's nice that other tools support it, but I don't have enough interest in it personally to do the work to add this feature. We have OpenAPI support which is already a well-recognized standard description format. I'd consider  merging a PR though if someone else wants to put in the work.
