### ISSUE TITLE
500 Internal Server Error in case of incorrect JWT

### ISSUE THREAD

**Issue by NikolayS** [begriffs/postgrest#502]
If I use something meaningless as JWT:
```http
GET /test HTTP/1.1
Host: localhost:3000
Authorization: Bearer dsfsdf.sdfsdf.sdfsdf
```
response is:
```http
HTTP/1.0 500 Internal Server Error
Date: Sat, 20 Feb 2016 23:11:11 GMT
Server: postgrest/0.3.0.3
Content-Type: text/plain; charset=utf-8
```

like something is wrong on server side. Seems like the situation of incorrectly built JWT is not correctly processed in the code. Solution could be: try to base64decode of both two first parts of JWT token and if it fails, reply with `400 Bad Request` or smth more suitable.

**Comment by begriffs** [comment]
Tried this out today and I see what you mean. It's interesting that you can use a bigfakestring for the JWT and it behaves OK, but once it has those dots in it then it dies on the server with

```
uncaught exception: UnicodeException
(Cannot decode byte '\xec': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream)
```

I agree that a 400 not a 500 error would be more appropriate. Since this doesn't cause a security problem or anything I'd classify it as a lower priority issue than some other ones right now, but it is a valid issue.

**Comment by begriffs** [comment]
Given the new code on the master branch when I try posting that bad JWT I get a 401 response with the body:

```json
{
  "message": "JWT invalid"
}
```

So I think we're all good now!

**Comment by NikolayS** [comment]
Great!
