### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by huangfushun** [begriffs/postgrest#516]
Tested by java code:
```
        String json = "{\"id\": 2,  \"name\": \"￥\"}";
		HttpPatch patch = new HttpPatch("http://localhost:5430/event?id=eq.2");
		patch.addHeader("Content-Type","application/json;charset=UTF-8");
		HttpEntity entity = new StringEntity(json, ContentType.APPLICATION_JSON);
		patch.setEntity(entity);
		CloseableHttpClient client = HttpClients.createDefault();
		try {
			CloseableHttpResponse resp = client.execute(patch);
			System.out.println("response : " + (resp.getEntity() != null ? EntityUtils.toString(resp.getEntity()):""));
			
			client.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
```
and return error:
```
response : {"hint":null,"details":null,"code":"22021","message":"invalid byte sequence for encoding \"UTF8\": 0xe5 0x27 0x3a"}
```
it worked before v0.3.0.4

**Comment by dnaq** [comment]
I think I've found the reason for this. In 7b92449 the author switched from using string concatenation to using Text.InterpolatedString.Perl6 to create the raw sql statements. The quasiquoter used does not encode text values as UTF8, thus generating invalid SQL that Postgres complains about.

I'm on mobile now, but the short term solution is to add explicit calls to Data.Text.Encoding.encodeUtf8 for parameters that can contain Unicode values, e.g.

_args = T.encodeUtf8 $ ...

in callProc.

The long term solution is to think over if the loss of type safety when switching to interpolated strings is worth it compared to the convenience in using them. In my opinion that's a no, since one of the pros of the strong typing in Haskell is that Unicode errors should be impossible to make.

**Comment by ruslantalpa** [comment]
@dnaq nice find, probably saved everybody a few hours of debugging.
should be easy to switch back

**Comment by begriffs** [comment]
@dnaq thanks for debugging -- I'll add a test and get rid of the interpolated strings.

**Comment by dnaq** [comment]
@begriffs no problem, thanks for your work.
