### ISSUE TITLE
Computed columns without views

### ISSUE THREAD

**Issue by nerfpops** [begriffs/postgrest#574]
In #443 @begriffs shows a neat way to add computed columns to a table via

    CREATE FUNCTION full_name(users) RETURNS varchar
        LANGUAGE sql STABLE
        AS $_$ SELECT $1.first_name || ' ' || $1.last_name $_$;

Adding a computed column like that is pretty cool because it allows one to add new data columns to a table without having to recreate a view and apply permissions to that view again. Having to recreate a view and apply permissions to it again because a column have been added or removed shouldn't be necessary. Creating rules on a table with "on select to users do instead", where I think one could add computed columns, also fails when the table contains dropped columns (!!).

There's just one catch when using functions: The computed column doesn't show up when not selecting that column directly, and that's counter-intuitive. In other words: Requesting /users doesn't return full_name.

I'm considering simply granting all permissions to the various roles on my api schema and let the views contain logic for what's accessible and what's not. Then I don't have to grant permissions again for the view whenever the underlying table is changed and the view is recreated. Something like this:

    GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA api TO customer;

But I'm really not sure if this is a good idea.

How do you guys deal with this?

Edit: It seems that the grant above is lost when recreating views :(

**Comment by SebAlbert** [comment]
For my part, I am using pgAdmin III and my workflow for altering a VIEW consists in copying, pasting and modifying the SQL statement shown by pgAdmin III when selecting the view. That way, the GRANT part is also copied and re-run.
I don't think this is a very elegant way either.

However, I wouldn't want to care for all permissions manually like you described. I really like to leverage built-in capabilities of the database, including role level permissions in this case. But if you have to do so anyway because of row-level security etc., then it may be not so much of an additional hazzle for you. But you have to be very cautious when implementing your checks.

**Comment by nerfpops** [comment]
Thanks! I'm using DBeaver because it's interface is so nice, but it doesn't provide script generation for updating views. I'll just switch to pgAdmin III. Leaving this issue open in case someone have other solutions.

**Comment by nerfpops** [comment]
Perhaps PostgREST could detect all computed column functions, like the example given by begriffs, and expand `select=*` to `select=*,full_name`. Now _that_ would be awesome! Then I wouldn't needs views or an api schema.

**Comment by ruslantalpa** [comment]
I think * is kind of a hack and you should always specify in your requests exactly what you expect, using * might break in the future your client code (maybe you drop/rename a column).
Leaving that aside, the way it currently works is very similar to how * in sql works, it will not return you your computed columns, you have to manually specify them to get them, exactly like &select= parameter works.

**Comment by nerfpops** [comment]
Alright, thank you for your answers.
