### ISSUE TITLE
How to implement 'logout' feature

### ISSUE THREAD

**Issue by geohuz** [begriffs/postgrest#581]
I'm very new to JWT and postgrest, so the following question may seem stupid: Is there any example for 'logout'?  Thanks for help!

**Comment by eric-brechemier** [comment]
Using plain JWT, logging out would simply be 'forgetting' the JWT on the client side. But then you will need a way to retrieve the same JWT from the server the next time you log in, i.e. an extra layer of authentication.

**Comment by geohuz** [comment]
Ah, I got it! BTW, I noticed the token generated from server is the same string for the same user/pass, only if I change the -j parameter. Is there best practice to make it 'more' secure? (i.e change the jwt secret automatically). Thanks!

**Comment by eric-brechemier** [comment]
The best practice is to generate a binary secret: https://github.com/begriffs/postgrest/issues/473
but sadly, this currently results in a corrupted secret due to a pending bug: https://github.com/begriffs/postgrest/issues/495

In the meantime, I would suggest choosing a long enough passphrase in plain text, rather than a single word, for your secret.

**Comment by begriffs** [comment]
For voluntary client logout discarding the jwt on the client side will work. For forcible server-side user banning there is a PR open to help with that. Closing this issue. If you have more questions about JWT feel free to ask.
