### ISSUE TITLE
Execute privileges for functions

### ISSUE THREAD

**Issue by ruslantalpa** [begriffs/postgrest#598]
By default, if a user has usage privileges in a schema he also has execute privileges on all functions in that schema because by default on function creation, execute is granted to public.
You need to issue `revoke all privileges on function login(text, text) from public;` for example after function creation, and later, manually grant execute to specific users.
i.e. in the users example, at the end of the doc, `grant execute` is useless/misleading since anon already has access to those functions.

**Comment by nerfpops** [comment]
Ouch. [I'm planning on writing a trigger](http://stackoverflow.com/questions/36964803/how-to-enable-row-level-security-by-default) (some time in the future) that by default enables row level security for every table I create, since I might easily forget to enable it myself. Perhaps some common security triggers would be a useful addition to the docs?

**Comment by ruslantalpa** [comment]
As a side note it could be useful, but at the same time i think the examples should use explicit `grant/revoke` statement to make it clear what is going on.

**Comment by begriffs** [comment]
Closing this issue here, please open this kind of thing on the new https://github.com/begriffs/postgrest-docs repo.
