### ISSUE TITLE
Prefer: return=representation AND Prefer: plurality=singular

### ISSUE THREAD

**Issue by nerfpops** [begriffs/postgrest#627]
When patching, I'd like the patched row returned as an object instead of an object in a list.

Using fetch in JavaScript:

    var headers = new Headers()
    headers.append("prefer", "return=representation")
    headers.append("prefer", "plurality=singular")
    fetch("/api/row?id=eq.123", { headers: headers, method: "PATCH", body: {} })

Prefer is then merged into a single header separated by a comma:

    prefer:return=representation,plurality=singular

But this results in 204 No Content.

**Comment by ruslantalpa** [comment]
That's because the value of the header should be

`Prefer: return=representation;plurality=singular`

**Comment by nerfpops** [comment]
Now it returns the row in a list.

**Comment by ruslantalpa** [comment]
Looks like this line https://github.com/begriffs/postgrest/blob/master/src/PostgREST/App.hs#L148
hardcodes the fact that when doing update, you always get a list ... that is probably done because we never know how many rows will be updated.
More thought should be put into the idea that we must consider "singular" header ... i.e. you could issue a PATHC, send singular header but actually update a lot more rows

**Comment by nerfpops** [comment]
Personally I don't mind if the separator is comma or semi-colon, but accept-encoding and accept-language uses comma as their seperator and the [fetch spec](https://fetch.spec.whatwg.org/#concept-header-list-append) states that additional values for the same headers should be separated by a comma.

Since a SELECT call might also return additional rows, and plurality=singular in that case just returns the first, I don't think it would be big issue allowing plurality=singular on a patch call that might update multiple rows.
