### ISSUE TITLE
JWT role invalidation

### ISSUE THREAD

**Issue by daurnimator** [begriffs/postgrest#631]
I'm trying to figure out how to deactivate (but not delete) user accounts. e.g. if an employee leaves.
First step will be adding an 'active' column to my users table. 

Using this, you could check that the user is active when you fetch their user id:

```sql
create function core.current_setting_no_throw(s text) returns text
	language plpgsql as $$
	begin
		return current_setting(s);
	exception
		when undefined_object then return NULL;
	end
	$$;

create function core.postgrest_user() returns uuid
	language plpgsql as $$
	declare
		_id uuid;
	begin
		_id = core.current_setting_no_throw('postgrest.claims.user_id')::uuid;
		if _id is null then
			return null;
		elsif exists(select 1 from core.users where id = _id and active = false) then
			raise invalid_password using message = 'your user is inactive';
		end if;
		return _id;
	end
	$$;
```

However this does nothing to change/remove the `role` that is restored by postgrest from their JWT token.
Postgrest needs a way to jump in and validate a role/JWT before it's used.

**Comment by djk447** [comment]
Just mentioned this in the gitter, but check out https://github.com/begriffs/postgrest/issues/529 has a similar feel. I solved this for now by adding a database role for every user, then granting group membership to certain users. I can share some of the functions etc that I made to make the process of role creation etc manageable if that would be helpful. It just feels a bit awkward because of the whole role/cluster thing. But it does allow you to do individual GRANT/REVOKE for the users, so even if the employee doesn't leave but their permissions change it makes it easier. If your app isn't horribly large the role system should be a perfectly viable way of handling it. I still think that a hook before the SET ROLE statement would be useful for other reasons and make this a little cleaner, but this way definitely works.

**Comment by daurnimator** [comment]
> I solved this for now by adding a database role for every user, then granting group membership to certain users.

For my original design I discussed this in the #postgresql irc room, and they said its a bad architecture from their perspective: something about how the user catalogue has locks around access and is shared between databases.
Not to mention, I think I ran into issues inheriting from a system catalogue; which makes adding extra user attributes error prone.

**Comment by djk447** [comment]
So I'm going to write this with the caveat that I'm not really using this for public signup, so it's a different sort of system, users will be added by specific classes of users that already exist. And in terms of user names, I just use the email directly, because that was good enough for me to start. You could, however, generate a random username for use internally when a new user signed up, insert it into the user table, wait until they confirm their email or something and then create the role. Hell, I don't see any reason you couldn't just use a uuid generated when they make their account. Especially if you wanted to be able to add multiple emails to login by. For me the single email was enough. 

The user is always created in the anon user group, has no ability to login or do anything else really, the authenticator can switch to that role, but relies on a different user with ability to grant the roles available to your application to grant them membership in a role, but that should be limited in its scope. So I tried to limit the work that was happening as a superuser. 
```SQL
--as a superuser or user with CREATE ROLE ability:
CREATE OR REPLACE FUNCTION create_role( n_role_name TEXT) RETURNS void as $_$
DECLARE
    use_sql TEXT;
BEGIN
    use_sql := 'CREATE ROLE ' || quote_ident( n_role_name )||' WITH NOSUPERUSER NOCREATEROLE NOCREATEDB NOLOGIN NOBYPASSRLS NOREPLICATION IN ROLE anon;';
--should throw an error if someone tried to add permissions somehow, though quote_ident should help
    EXECUTE use_sql;

    use_sql := 'GRANT ' || quote_ident( n_role_name )|| 'TO authenticator;';
    EXECUTE use_sql;
    UPDATE auth.users SET role_created=true WHERE email=in_role_name;
END;
$_$ LANGUAGE plpgsql SECURITY DEFINER;
REVOKE ALL ON FUNCTION create_role (n_role_name TEXT) FROM public; --just to make sure
GRANT EXECUTE ON FUNCTION create_role (n_role_name TEXT) TO new_user_creator, administrator;
--assumes you have a role, perhaps a server that can create a new user and that the administrator can also do this. 
```

Then we have a function that handles granting roles to the user, this isn't created as a superuser but just as the administrator of the database for the app, the administrator user has access to everything on the database for the application, but not for other databases. It also has access to the other roles that I've created specifically for the app, like a manager who can grant their role to other managers and field_tech to people in their company but not outside of it. 

```SQL

SET ROLE administrator;
CREATE OR REPLACE FUNCTION grant_helper(  n_role_grant user_type, n_role_name TEXT) RETURNS bool as $_$
BEGIN
    UPDATE auth.users SET role_type=n_role_grant WHERE email=n_role_name;
    RETURN true;
END;
$_$ LANGUAGE plpgsql SECURITY DEFINER;
REVOKE ALL ON FUNCTION grant_helper (n_role_grant user_type, n_role_name TEXT) FROM public; --just to make sure
GRANT EXECUTE ON FUNCTION grant_helper(n_role_grant user_type, n_role_name TEXT) TO  manager;

SET search_path TO auth, public;
CREATE OR REPLACE FUNCTION grant_role( n_role_grant user_type, n_role_name TEXT) RETURNS void as $_$
DECLARE
    use_sql TEXT;
BEGIN

    use_sql := 'GRANT ' || quote_ident( n_role_grant::text )||' TO ' || quote_ident( n_role_name )||';';
    EXECUTE use_sql;
    PERFORM auth.grant_helper(n_role_grant, n_role_name);
END;
$_$ LANGUAGE plpgsql ;
REVOKE ALL ON FUNCTION grant_role (n_role_grant user_type, n_role_name TEXT) FROM public; --just to make sure
GRANT EXECUTE ON FUNCTION grant_role (n_role_grant user_type, n_role_name TEXT) TO  manager;
```
You can easily make analogous functions for dropping roles or revoking permissions. 

All this said, I don't think this is the best solution, using hooks would be much better eventually, there also should be better checks for whether the user exists before it's created or anything, but I sort of didn't care if it just errored in that case. There is likely a way to break this, I tried to make it hard, but probably isn't remotely perfect. So I'd listen to the folks at the postgres IRC-perhaps it could be done as a stopgap, but I wouldn't use it long term. I still think that adding some sort of hook/extension point to the PostgREST bit is a much more elegant way of doing things...and if there are thoughts on why this is horrible, please do let me know.

**Comment by begriffs** [comment]
The master branch now supports a parameter called `--pre-request`. You give it the name of a schema-qualified stored procedure and it will call the procedure right after authentication but before the any data is fetched. This function can do anything it wants, including changing to another role or raising exceptions to stop the request.

If the built-in postgres permissions system isn't enough for your use case then this extra procedure should do the trick.
