### ISSUE TITLE
Support configuring 307 See Other for POST requests

### ISSUE THREAD

**Issue by jackfirth** [begriffs/postgrest#654]
#592 added support for creating rows with html form requests, but the response is empty so doing it from a browser without AJAX is a bit painful. Luckily, the [303 See Other](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection) response code can be used to tell browsers that the post was successful but they should get their response from somewhere else.

It would be great if I could somehow tell postgrest "when people post html forms to /emailsignups, 303 redirect them to /signup-success"

**Comment by begriffs** [comment]
That's an interesting idea. I agree that the current redirect-to-blank-page behavior is annoying. What if you used front end javascript code to handle the form submission and changed the browser location yourself on successful post?

Another technique would be to use nginx to override the response for a particular route.

If you're thinking that postgrest could send a custom Location header and redirect status code how would you propose to configure the specific redirect per route? Also postgrest wouldn't currently expose a nested route like `/emails/signups` since the route would be the name of a table or view. (`/signups` for instance)

**Comment by jackfirth** [comment]
Frontend code and a proxy could both do this just fine. I think there is value in having Postgrest handle it out of the box, because it could be much simpler to configure. A yaml file mapping tables to redirect endpoints ought to be enough for most use cases:

```
post-redirects.yml
--------------------
signups: <url-for-some-signup-success-page>
invitations: <url-for-some-invitation-successfully-sent-page>
...
```

Then tell postgrest about the file on startup with some flag like `postgrest --post-redirects-file post-redirects.yml`. There's a good argument that this should be a proxy's responsibility, however the way postgrest handles posting of html forms feels incomplete without this.

**Comment by begriffs** [comment]
It does feel extremely natural for a proxy though, like something they're built to do well with a DSL for it and everything.

However one thing I can do on the postgrest side is to document how to use nginx with postgrest. Using a proxy has come up as the answer to many issues but our docs are total crap for this right now.

So I'm leaning toward keeping the core postgrest code simple for now, but feel free to re-open this issue if you think of more arguments to add the functionality.

**Comment by jackfirth** [comment]
Makes sense to me!
