### ISSUE TITLE
update/delete entity record and relational records

### ISSUE THREAD

**Issue by rkoberg** [begriffs/postgrest#667]
Pretty sure I know the answer to this (which would be "no") and it is not RESTful, but was wondering (hoping against hope) if something like the following is possible. I see in the docs where something like this could almost be accomplished with views, but not completely and only in simple (RESTful) ways. Similar to https://github.com/begriffs/postgrest/issues/286 and using those tables:

```
CREATE TABLE demo.participant(
  id BIGINT DEFAULT,
  name VARCHAR(255) NOT NULL
  );

CREATE TABLE demo.event(
  id BIGINT DEFAULT,
  title VARCHAR(255) NOT NULL
  );

CREATE TABLE demo.event_participant(
  event_id BIGINT NOT NULL REFERENCES demo.event(id),
  participant_id BIGINT NOT NULL REFERENCES demo.participant(id),
  PRIMARY KEY(event_id,participant_id)
  );
```

Let's say that a participant can have several events and they can add/remove events. Let's also say that the participant record can be edited in the same form that contains the editable list of events. So participant X changes their participant data and adds three events to their set of events. Request data to the api server would be:
{name: "foo", events: ["id1", "id2", "id3"]
This can't be handled by a view because the participant would need to use a PATCH, and the events would need a POST, right?
Later the participant comes back, changes their name, adds one event, and removes one event, so request would be:
{name:"bar", events: ["id2", "id3", "id7"]}
As I see it now, I would need to make the following requests from the client:
- PATCH the participant record in "participant"
- DELETE the removed event from "event_participant"
- POST the new participant/event to  "event_participant"

Is there some way to do this in one request? (Hoping I am missing something.)

**Comment by ruslantalpa** [comment]
@rkoberg this is an area (mutating multiple tables) that was not yet developed to have the capabilities of "GET" requests.
I understand where you are coming from i think, you are thinking of a custom api where you would send one request with a bunch of data that gets split up and multiple queries are executed to mutate a bunch of tables.

PostgREST does not (yet) have those kind of capabilities. This area needs exploring.
You are right about needing to make multiple requests from the client to `link` the records from events and participants tables.

There is a possibility though that something close can be done with views and triggers that would allow you to do a single request.

Let's first define the problem,
You want when reading `participants` to have a field `event_ids:[....]` and when updating a participant, you want to send the `events_ids` field and have the backend remove all the links from `event_participant ` and add the new ones (using `event_ids`)

For this first you create a view called participants that has all the columns from the source table and adds the `events_ids` column (by joining). If it's done right i think this view will be autoupdatable except for the events_id column.

For insert/update paths, you will need to create a `before update` trigger that will take the data from new_ids column, execute the delete/insert queries then let the normal update process continue.

This process i described above i did not test but i think it will work, as i said, it needs exploration :)

**Comment by encryptedcommerce** [comment]
I generally prefer to do these types of operations on the application side for an API / web service instead of on the database.  I have heard and read arguments (that I agree with) stating the value of a separation of concerns between the data store and the business logic.  Though a lot of these things can certainly be done through view, triggers, and stored procedures, I prefer an architecture that uses a database as a pure data store, possibly interacted with through an Object-Relational mapping, and lets the application code handle the business logic behind responding to API endpoints. If there are things that PostgREST does not offer out of the box, then perhaps we could extend it or find some other way to respond to API endpoints with custom code.  I think this would be an important functionality to have.  Then we're free to create an endpoint where we can submit all of the data we want in a single HTTP request and have all of the necessary operations performed.

Although the example use case given might not necessarily be ideal (do we REALLY want people to change their name and the events they're attending on the same form? I don't think I've ever seen such a user interface on sites before, since it's a bit confusing information architecture from the user side to perform both of these operations at once.  However, it's a good example of how we might want to handle several concurrent operations that might not be supported out of the box with PostgREST.

I will look at how easy it is to extend PostgREST to handle custom responses to API end points without needing to have a separate process on a different HTTP server.

**Comment by begriffs** [comment]
You could also denormalize the database and add an events json array field to the participant table. You'd probably have to use a trigger to enforce the "foreign key" constraint that array elements refer to real event ids, but this technique would allow you to read or update participants and their events with single form.

As noted, the biggest impediment to updating multiple tables from the front-end is our lack of transaction control in the exposed API. I'm interested in seeing whether HTTP2 can help us cleanly support transactions. For instance each [stream](https://tools.ietf.org/html/rfc7540#section-5) could indicate a transaction, and the frames within it could be actions.

**Comment by ruslantalpa** [comment]
@encryptedcommerce the whole point of PostgREST is to NOT treat the database as a pure data store.
There is a reason people worked hard on features like views/triggers/constraints.
What you refer to as business logic is actually data logic, there is nothing `business` about keeping the data consistent actors multiple tables.
I've also thought recently why there is such a tendency in the dev community to prefer to do everything in the "application side". So i am going to take a guess and say ... you grew up with mysql (so did i, could not afford oracle) :) am i right?
For a very long time Mysql did not have views/triggers/stored procedures/foreign keys so ppl did everything in the code. By the time they were implemented (and not very performant) and became default, 10 years had passed and ORM took over (because it had to compensate for the lack of features) and there were countless tutorials written how to do things "the right way" and no one stopped to think if it's the right way forward (do everything by hand in code).

Embrace the DB (PostgreSQL) and you will see how much code (in the application side) it makes unnecessary

**Comment by jcrben** [comment]
In theory, it seems like constraints should express some of the intent here? We shouldn't have to write triggers. A good ORM figures this out based upon the constraints without boilerplate.

If nothing else, perhaps Postgrest could have a feature which automatically sets up the triggers.

**Comment by ruslantalpa** [comment]
@jcrben please show me that "good ORM" :)

**Comment by jcrben** [comment]
@ruslantalpa I've used a bunch, but SQLAlchemy is the one I'm using right now and it's OK altho I'll admit it's got kind of a steep learning curve. 😄 Still, I'd rather not use SQLAlchemy for simple CRUD updates - planning to use it for async work or complex business logic

I'm looking at using PostGraphQL right now as it seems that it allows for efficiently persisting an entity including its related entities, but I haven't dug into quite enough yet to see if it'll do what I want...

**Comment by begriffs** [comment]
I'm cautiously closing this issue, since it appears to be a special case of https://github.com/begriffs/postgrest/issues/286
