### ISSUE TITLE
Consider adopting `PostgreSQL JSON Web Token Serialization Specification`

### ISSUE THREAD

**Issue by bobcolner** [begriffs/postgrest#674]
The [PostGraphQL project](https://github.com/calebmer/postgraphql) has proposed a standardized spec for handling JWT's in Postgresql API servers:

[PostgreSQL JSON Web Token Serialization Specification](https://github.com/calebmer/postgraphql/blob/master/docs/pg-jwt-spec.md)

As Postgrest is the most mature postgresql API server, I think it would benefit the greater community to consider adopting this spec. The spec is itself based off (but a little difference naming conventions) the existing postgrest implementation.

The big win for end-users would be the ability to expose both a REST API *and* a graphQL API from the same postgresql DB -using a single authentication mechanism.

**Comment by begriffs** [comment]
Looks like that doc proposes these differences from what we already do

* (As you mentioned) Setting `jwt.claims.xyz` rather than `postgrest.claims.xyz`. This makes sense because they are specifically claims from jwt.
* Setting those variables as `local` -- I think we currently do this only for `set role` but I'd have to double check.
* There's no mention in the spec about proper quoting of the claim names in sql, but we take care of that as well (aka if a claim has a sql-injection kind of name)

Seeing as we're coming up to a 0.4 release we can consider making this backward-incompatible change. I'll let other people chime in.

**Comment by ruslantalpa** [comment]
We can have a kind of standardized naming things but i don't particular like the proposed spec, it only refers to jwt, and we need much more, we need cookies, jwt, headers, maybe other things. It should be more like

`apiserver.jwt.claims` (or without the claims) `apiserver.headers` `apiserver.cookie` ... 
the spec needs to consider all the properties of a request and have a way to specify that

**Comment by bobcolner** [comment]
@calebmer: FIY we are discussing implementing your _PostgreSQL JSON Web Token Serialization Specification_

**Comment by begriffs** [comment]
@bobcolner, @calebmer any thoughts on the desired spec and @ruslantalpa's comment? We're getting ready for the postgrest 0.4 release and now would be a good time to make breaking changes.

**Comment by ruslantalpa** [comment]
@begriffs i suggest this needs to go in 0.4 and let's have it like this (samples)
```
request.jwt_claims.user_id
request.cookies.mycookie
request.headers.x_forward_ip
```

then we can have a set of helper functions (in a separate schema like `request`, similar to the sql jwt lib) and be able to call them like `request.get_cookie('mycookie')` `request.get_jwt_claim('user_id')` ...

**Comment by calebmer** [comment]
Looks good 👍

The one thing I may add is maybe have `request.jwt.claim` (to allow for other information like `request.jwt.algorithm`). Also, does singular form make sense to you? So `request.header` vs. `request.headers`.

If anyone wants to write a spec, and or a utility SQL script it looks great 👍
