### ISSUE TITLE
Docker Builds Failing

### ISSUE THREAD

**Issue by jhr007** [begriffs/postgrest#730]
https://hub.docker.com/r/begriffs/postgrest/builds/

Updating `ENV POSTGREST_VERSION 0.4.0.0` in Dockerfile caused the builds to fail, because there isn't a 0.4 release on github.

**Comment by begriffs** [comment]
That's true. Waiting to release the 0.4 binaries after the new docs are ready. The docs in progress are at https://postgrest.readthedocs.io/en/v0.4/ and when they're ready I'll point postgrest.com at it and build the binaries.

**Comment by jhr007** [comment]
What are your thoughts about having a docker tag, **latest** that tracks the master branch?

For posterity, this is the Dockerfile I used to build from the master branch. **It made a 5Gb docker image, so don't use it in production.** Note that I'm using the `fpco/stack-build` image so stack & haskell would already be there. 

```docker
#Dockerfile.development
FROM fpco/stack-build 

ENV POSTGREST_REPO_URI https://github.com/begriffs/postgrest.git

RUN apt-get install -y  libpq-dev && \
    cd /srv/ && \ 
    git clone ${POSTGREST_REPO_URI}

RUN cd /srv/postgrest && \
    stack install --allow-different-user --local-bin-path /usr/local/bin

CMD exec postgrest -c /etc/postgrest/postgrest.conf

EXPOSE 3000
```

**Comment by begriffs** [comment]
I've wanted that for a while – a fully up-to-date image on the *latest* tag built off master. I didn't know how to create a reasonably sized image though. That's why it currently downloads pre-built binary releases rather than including the whole Haskell build environment.

Is there a way to run different commands in the Dockerfile depending on a chosen "environment?" We could have a special development image that is big but up to date, and a small production image for each release. Any idea of the best way to do that?

Alternately we could find a way to always build from source in the Dockerfile but do a better job cleaning up all the build artifacts so that the resulting image is small.

**Comment by jackfirth** [comment]
You can use the [split image approach](https://www.fpcomplete.com/blog/2015/12/docker-split-images) where you have two docker images - one that compiles a binary during image build and puts the binary into a volume when run, and another that simply takes a pre-built binary and sticks it into a tiny base image.

If you take this approach, I'd recommend not doing a git clone in the docker build and using the COPY instruction assuming you're building from the repo root. Additionally, you'd have to build the images in CI and push them to docker hub yourself instead of relying on docker hub's automated builds.

**Comment by begriffs** [comment]
@jackfirth good tip. The docs there talk about stack support as well for `stack image container`.

**Comment by jhr007** [comment]
Do you want to target a CI improvement for the .4 release? 
For reference...
[CircleCI](https://circleci.com/docs/docker/) has docker support as well. 
[Stack's Base Docker Images](https://docs.haskellstack.org/en/stable/docker_integration/#image-repositories) 
[Docker build docs](https://docs.docker.com/engine/reference/commandline/build/)

Should I go ahead and create a PR to add `-c /etc/postgrest/postgrest.conf` to the Dockerfile?

**Comment by jhr007** [comment]
I've got CircleCI  building `Dockerfile.development` with dependencies built inside. That docker image is then used to build postgrest so it can be added to the simpler `Dockerfile` image and pushed to Docker Hub. 

It's more of spike than a work in progress... 

I now understand why I've seen some use a Makefile to manage various docker build/run commands.
A lot of the circle.yml's shell commands could be broken out into actual shell scripts or even a Makefile. 

I didn't grok `stack docker` deep enough to answer: Could `stack` manage the docker image & circleci's caches better? Any conflict w/ CircleCI's docker limits to work around?
 
[DockerHub](https://hub.docker.com/r/jhr007/postgrest/) - Note 'latest' in 'tags' is deployed on master commit
[CircleCI](https://circleci.com/gh/jhr007/postgrest) - builds 
[io.PostgREST](https://github.com/jhr007/postgrest) - My fork, soon to be known as io.PostgREST :smile:

**Comment by jackfirth** [comment]
Stack's docker images are more for running the stack build process inside a container than for actually producing docker images.

Instead of a makefile, I recommend using `docker compose`. You setup a split image build somewhat like this:

```yaml
version: "2"

services:
  builder:
    build: /path/to/builder
    volumes:
    - ./runtime/bin:/output-bin
  runtime:
    build: /runtime
```

Instead of the first image building a dockerfile, it builds a binary and sticks it into a volume which maps to the host directory `./runtime/bin`. Then, `./runtime/Dockerfile` would specify to use the binary in `./runtime/bin`. So building your image is `docker-compose run builder && docker-compose build runtime`.

**Comment by jhr007** [comment]
PR : #737 

- The all Docker build is no more...
    - Couldn't get PostgreSQL db into docker image's tests without adding env var to Tests
    - Back to CircleCi's ghc image, can use a git branch to test newer versions from https://circleci.com/docs/build-image-precise/#haskell
    - Moving test commands into a scripts led to false positives in build, script exited correctly, but commands inside failed, so I didn't trust my bashfu to trust it would halt 
        - Plus it ended up a single cluttered entry on the circle build, made determining which command in script is causing errors harder
    - There's some repeated code between circle.yml, scripts/, Dockerfile.development
    - Ignore these errors during docker build image, all docker images made on CircleCI are immutable:
    ```
    Error removing intermediate container 2d199a8e8ec1: rmdriverfs: Driver btrfs failed to remove root filesystem 2d199a8e8ec13d0d8f5b48e555d04c6c677e3024acfef61f4b7ddd83c9c6483e: Failed to destroy btrfs snapshot /var/lib/docker/btrfs/subvolumes for e8505114d839823bb265bb5cc0e15cc141293a42307843bff69f6bce935399b9: operation not permitted
    ```

Dockerfile.Development
    - Work in process
    - Fell out of scope after switching back to all CircleCI build...
    - I'll revisit during v4 documentation for Docker
    - !DRY, Repeats the build code in scripts/ and circle.yml
    - Could use volumes into container to import stack/cabal deps, it'd make cached builds somewhat faster    
    - Document:
        ENV vars from Dockerfile.development:
        POSTGREST_SRC 
        RELEASE_DIR

- Post Mortem of Builds-in-Docker circle.yml, branch jhr_circleci_docker
    - Builds everything in Docker image, circle build container doesn't even install ghc
    - build times: 1 Hour 15 minute to build image, 7-10 mins after image cached, not caching anything outside docker image
    - 5Gb Docker Development image (4Gb base image) cached, find a smaller docker image?
    - Single file cache restore(but 5gb) -vs- multiple cabal deps
    - Cache busting is hard... :) scripts/init_docker.sh helps manages a cached docker image

**Comment by ruslantalpa** [comment]
we now have automated release build (in docker :) )
