### ISSUE TITLE
Documentation Update: user passwords given out on GET request 

### ISSUE THREAD

**Issue by tocttou** [begriffs/postgrest#770]
In docs for ["Multiple Tables Insertion or Update"](http://postgrest.com/api/writing/#multiple-tables-insertion-or-update), the view is created as:

```
CREATE VIEW signup AS
    SELECT
        c.name AS company_name,
        u.name AS user_name,
        u.pass
    FROM
        public.users u
        JOIN public.companies c ON c.id = u.company_id;
```

This view is exposed using the `/signup` endpoint and it would give out `u.pass`, but `u.pass` is required to be in the view if we have to update that field.

Would it be better to use some other example in the docs or probably replace it with / add information about using pre/post triggers or stored procedures via the rpc interface to update multiple tables at once?

Thanks

**Comment by begriffs** [comment]
Thanks for reporting the problem. Those docs will soon be replaced by https://postgrest.readthedocs.io/en/v0.4/

I have intentionally omitted some of the more tricky auth examples in the new docs so that we can add them later after more careful testing. I welcome your help as we develop the new auth docs.

I'll switch the domain postgrest.com to point at the new docs after the 0.4 release (see [milestone](https://github.com/begriffs/postgrest/milestone/1)).

**Comment by begriffs** [comment]
Docs are now replaced on http://postgrest.com

Would love if you could look them over for any other security faults if you get the chance.
