### ISSUE TITLE
GraphQL Proxy

### ISSUE THREAD

**Issue by samgaw** [begriffs/postgrest#786]
I remember seeing references to an Openresty proxy that was rewriting queries to/from GraphQL but I never had a chance to have a look at it properly.

Whats the latest with that? Has it disappeared in favour of a different approach?

**Comment by ruslantalpa** [comment]
http://graphqlapi.com/graphql/ :)

**Comment by samgaw** [comment]
Done :)

I found a Docker image that I pulled down, and quickly went through the config to see what it was doing and try to point it at my Postgrest instance but I'm not sure if everything is bundled in or if I'm just looking in the wrong place. Is the Lua lib called in graphql.conf missing?

**Comment by ruslantalpa** [comment]
Just curious how did you get to those images, they are public for easier onbording but not very useful without documentation, and by config you mean you looked at the image at the openresty configuration files, right?

**Comment by samgaw** [comment]
The URL you pointed me to calls the project sub0, and there's a public repo on Github that you committed to referencing the images in the README. But if I'm not supposed to see them, I'm happy to delete it image on my machine and wait patiently until it's _officially_ public 😇 

But yeah, the Openresty graphql.conf is calling a Lua lib called sub0 that I can't find it to try to understand how it works. According to the comments that's how it generates the schema.json file?!

**Comment by ruslantalpa** [comment]
Well, the images are public, it's ok to see them, they will become "developer kit" images eventually.
The reason you do not see the sub0 lib is because you are not supposed to :) since that is the "value proposition", it's compiled into openresty directly.
PS: I sent you an invite (please close this issue)

**Comment by derekjwilliams** [comment]
ruslantalpa - very interested in getting an implementation of the graphql project up and running, but it looks like https://graphqlapi.com/graphql/ is no longer responding :( any thoughts?  Want to put a relatively unambitious graphql implementation on top of postgrest.  If the team needs any help, let me know

**Comment by ruslantalpa** [comment]
@derekjwilliams that was just a landing page that i no longer needed and removed it, you can just go to the homepage and add your email to the list https://graphqlapi.com/.
I am in the process of writing docs and tutorials now, then i will begin slowly sending invites and onboarding people since this is not a SaaS offering but a developer stack and it's not as simple as clicking a few buttons :)
