### ISSUE TITLE
Malformed nested JSON error

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#791]
@diogob this one seems like your specialty, a bug whose solution involves a nice refactor.

`/foo?id=0` throws a weird parse error with json inside json:

```
{"message":"{\"details\":\"unexpected \\\"0\\\" expecting \\\"not.\\\" or operator (eq, gt, ...)\",\"message\":\"\\\"failed to parse filter (0)\\\" (line 1, column 1)\"}"}
```

One way to attack at the root of the problem is changing the type of `errResponse` in App.hs to take a structured error type rather than text. Something like

```haskell
GeneralError {
  message :: Text,
  details :: Maybe Text,
  hint :: Maybe Text,
  code :: Maybe Text
}
```

Then follow the type errors throughout app/querybuilder etc and then all the malformed error anomalies should be fixed.

**Comment by diogob** [comment]
@begriffs nice one! I'll work on this :D

**Comment by begriffs** [comment]
Any progress on this one?

**Comment by diogob** [comment]
I've started on it, will work a bit more during the weekend. Hopefully I'll have something to show next week ;)

**Comment by diogob** [comment]
@begriffs the refactor grew a bit since I started. I saw a good opportunity to overhaul our error handling that has been growing in complexity lately. You can take a look at my branch here: https://github.com/diogob/postgrest/tree/refactor_error_type

My idea is to extend `ApiRequestError` and capture errors with a richer semantic to achieve two goals:
1. Isolate the concern with error formatting inside the Error module. Doing so will avoid the use of maybes in the type and will allow to propagate only error types instead of texts.
2. Avoid use of Parsec error types to carry error information beyond our Parsers module, in this way the Parsers module acts more as an anti-corruption layer hiding Parsec details.

I still have several commits to go, since right now the code is still a bit messy, but wanted to sync with you on these goals.

**Comment by begriffs** [comment]
Yeah that sounds good, simplifying the types and encapsulating each part. Thanks, this will be great.
