### ISSUE TITLE
Startup too long when connecting postgresql behind pgbouncer

### ISSUE THREAD

**Issue by TNTest** [begriffs/postgrest#796]
My envirement is something like this:

postgrest  -->  pgbouncer  --> postgresql

My startup script:
```
/postgrest "postgresql://<server_host:port>/user20170113074830lqgjyiceuser=user20170113074830lqgjyice&password=123456" --port 3000 --schema user20170113074830lqgjyice --anonymous user20170113074830lqgjyice --pool 100
```
After 8~12s passed, the rest api is ready to go. Why it takes so long?  (Connecting another 

postgresql directly is less than 1s)
Since no log output,  I tried using strace to determine the problem.  Many poll calls timeout. I am not sure it is the problem.  Please see the attachment:

[postgrest_trace.zip](http://note.youdao.com/yws/public/resource/b7d2a954f5d1d9e3c430560720d0ccab/xmlnote/3E701E51F9F94462B4F7DF2D85D162FA/5880)

Envirement Info:
* OS:  ubuntu 14.04
* postgrest: 0.3.2.0, 0.4.0.0
* postgresql: 9.5.3
* pgbouncer: 1.7.1

**Comment by ruslantalpa** [comment]
First make absolutely sure that the problem is pgbouncer and not your database schema, i.e. first point postgrest to pgbouncer that is connected to postgresql, then point postgrest directly to the exact same database. Once you confirm that it's pgbouncer, try this.

connect manually (psql or something) to pgbouncer, and execute queries one by one from this file https://github.com/begriffs/postgrest/blob/master/src/PostgREST/DbStructure.hs
these are the queries that are executed at startup. See which query exactly is causing the slowdown.

Once you determine that, come back here and we can investigate/brainstorm from that point on.

Do you have a lot of tables/views in your database? I've seen these queries being slow on databases that have thousands of tables/views, maybe this is your problem and not pgbouncer

**Comment by TNTest** [comment]
Yeah. U r right.  It's nothing about pgbouncer.  I tried to connect same db without pgbouncer,  as slow as before.  
And yes I have many tables/views,   10w+ totally (100+/user, 1000+ users).
I tried several queries you metioned above are slow(>2s).   
So Startup process costs 10~12s is expected according to my db?

**Comment by ruslantalpa** [comment]
yes, that is expected. You do not have a usual setup (db with thousands of schemas and tables)
It is possible to overcome this problem but you'll have to build your custom postgrest from source

the trick is this:
a) create a materialized view for each of those queries
b) change the postgrest source to execute `select * from someview` instead of running the query directly

this will make the startup fast and you only have to update from time to time your views whenever your schema changes (or you add a new client with his own tables)

PS: i am not sure why you have such a schema, do your clients really have that much diferent schemas (tables). would it be a better design to have a single table and have the data for all those users in that table and whatever custom fields one client might have just a json column for that?

**Comment by TNTest** [comment]
Well, we built multi-tanency solution by schema isolation here, that's why we have so many tables in one db. 

Thanks for your advise, I will have a try later.

**Comment by jtuskenis** [comment]
Hello,
we have problems with startup time too. Our DB consists of
schemas: 11 
tables: 562
views:  308
functions: 1579

We have one schema for postgrest with a single view.  The startup takes ~13 **minutes** !. I've checked the postgresql log. It seems all the time is consumed to execute the query attached
[postgrest_startup.zip](https://github.com/begriffs/postgrest/files/1035296/postgrest_startup.zip)
As I understand it is the query to build database model for internal use and OpenAPI. 

1. Is the startup time of 13 minutes normal for a database the size of ours?
2. Is there a reason postgrest scans all the objects in the DB and not only the ones in the schema it uses?
3. Do you have plans of some database schema caching to increase startup time?

One other misleading feature is that postgrest displays listening 3000 even before it is actually starts to listen for the port. netstat -an does not show port 3000 until the postgrest finishes loading. It should be trivial to fix that. 
I'm sorry I can't provide patches, because I don't know Haskell. Maybe in the future...

**Comment by ruslantalpa** [comment]
the source of this has just been tracked and there is an upcoming PR fixing it #926
