### ISSUE TITLE
Output RAML for schema info

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#8]
For the `OPTIONS` verb we should be outputting an industry standard to say the type of the response json as well as the parameters and versions accepted.

**Comment by smilliken** [comment]
There's a lot of fragmentation for schema description and serialization formats, and everyone's going to have a different favorite. I'd recommend designing this feature so it's easy to support other formats. Here's a few others:

https://capnproto.org/
https://github.com/google/protobuf/
https://thrift.apache.org/
https://github.com/Microsoft/bond
http://msgpack.org/

**Comment by affogato** [comment]
I'm very interested in this feature, and considering forking to implement it.
Has there been any progress, is anyone planning to or in the middle of working on it?

**Comment by begriffs** [comment]
Go right ahead, I'd love your help!

**Comment by jmealo** [comment]
@smilliken I'd like to see PostgreSQL to capnproto and protobuf in general, even if it's in an external package. @begriffs maybe once logical decoding and streaming are a thing this could be used for that depending on whatever haskell supports best.

**Comment by diogob** [comment]
@affogato @begriffs I'm considering starting some work on this feature. I agree (as mentioned above) that we should be able to change the output format. This should not be hard as ```src/PostgREST/PgStructure.hs``` already works with intermediary data types. Here's how I'm planning to implement:

1. Move ```TableOptions``` data type from ```App``` to ```PgStructure``` since it deals with intermediary data types.
2. Create a ```StructureConverters``` (name suggestions are welcome) and move the current ```ToJSON``` instances in there. Use this module for all output converters.
3. Create a second encoder (possibly RAML).
3.  Create a function that choses the encoder based on Accept headers (similar to ```contentTypeForAccept```).

Ideas? Feedbacks? If anyone is willing to discuss in finer details on gitter that would be great :D

**Comment by affogato** [comment]
@diogob That would be great. I don't know Haskell, so it was a bit ambitious. If I do get to it, I'd be using a script to convert from the current response to RAML or YAML.

**Comment by diogob** [comment]
@affogato if you implement any conversion script in this fashion please let us know here, it would be useful to implement the feature ;)

**Comment by begriffs** [comment]
Issue #144 is technically a duplicate of this one but that other issue has more recent momentum, so I'm closing this one. Let's move discussion over to 144.
