### ISSUE TITLE
Access HTTP headers inside PSQL

### ISSUE THREAD

**Issue by tjunussov** [begriffs/postgrest#800]
Like in Oracle PL/SQL via UTL_HTTP.GET_HEADER,  Is it possible to pass all header information to access them via psql function, smth like :
```
current_settings("http_host");
current_settings("http_referer");

```

**Comment by begriffs** [comment]
I thought there was a github issue about this already, but I can't find it...

Anyway, this is a good idea. We could prefix the name of the variables `request.header.http_referer` so that it is similar to how we store JWT claims as e.g. `request.jwt.claim.email`. One thing is we'll want to avoid making an extra roundtrip to the database to set the variables if we can help it, but it's probably doable.

**Comment by julesbou** [comment]
We could also set IP address of current request. It can be useful to save IPs in the database, for example when you insert a comment on a forum. Seems like it's not possible to do that with postgrest yet (I might be wrong).

**Comment by eldadj** [comment]
@ruslantalpa fyi

**Comment by ruslantalpa** [comment]
@eldadj see #849 
until it's merged, you can use the patch.

**Comment by spinus** [comment]
Looks like it's implemented and released in 0.4.1, should we close the ticket?
@tjunussov maybe you would like to verify?

**Comment by begriffs** [comment]
Closing. Can re-open if anybody runs into a problem with it.

**Comment by NikolayS** [comment]
For those (like me) who wonder how to use it, this one works:
```
current_setting('request.header.user-agent', true)
```
