### ISSUE TITLE
Where can I find the archive of postgrest docs?

### ISSUE THREAD

**Issue by sushantbajra** [begriffs/postgrest#805]

**Comment by uniphil** [comment]
Ouch, I thought this was just going to need a link to the [previous issue's solution](https://github.com/begriffs/postgrest/issues/789#issuecomment-274142120), but the docs' repository now seems to have obliterated `master`'s history for the `0.4` rewrite, so `0.3` docs can't even be found by digging through history.

There are no tagged releases of older docs either. The closest thing I can find is [this old branch](https://github.com/begriffs/postgrest-docs/tree/protect-validation/docs) which might be a bit behind the last release of `0.3`, but might have what you need, @sushantbajra .

@begriffs this is pretty alarming to me. I'm still using `0.3` because I run postgrest locally via the official docker images, which have not been updated to `0.4` yet (plus the change to a config file for 0.4 is a headache I don't even want to think about, since I configure production with environment variables on heroku).

Is there any particular reason why the docs are even in a separate repository?

**Comment by begriffs** [comment]
Don't be alarmed, I'll find the history in the reflog and tag it with v0.3.2.0. Should have tagged it earlier, my mistake.

I'm using master now to hold the latest changes and will use proper versioning through Read The Docs (RTD), so docs for all versions will be preserved and easy to find. The challenge between 0.3 and 0.4 docs is that I migrated to a new documentation system. For best usability I should probably port the 0.3 docs to RTD so that it can be selected from the UI.

We could look into pulling the docs back into the main repo, it's simpler in many ways. It used to be in the main repo, then got separated for two reasons which may or may not be as important as we thought:

1. Might want to store big assets like pictures in there (for instance all those pictures for the Heroku docs in 0.3) and don't want to slow people or CI down during the git clone.
2. Didn't want to litter the root of the project with docs configuration, but might not be a big deal.

**Comment by uniphil** [comment]
Alright, I am no longer alarmed 😌. Thanks @begriffs, and yay `reflog`!

I'd be down to help port the 0.3 docs to the 0.4 system. I have an idea to quickly resolve these "where did the docs go??" issues that I'll PR once you get the tag up.

**Comment by begriffs** [comment]
OK, I pushed a branch called "v0.3.2" pointing at the newest docs for the old version. Thanks for your offer to try porting them to Sphinx/RTD, that would be super helpful.

**Comment by sushantbajra** [comment]
Thanks @begriffs .

**Comment by begriffs** [comment]
The old docs are now a first-class citizen at https://postgrest.com/en/v0.3.2/

**Comment by sushantbajra** [comment]
Thanks @begriffs . I really appreciate that
