### ISSUE TITLE
Standardize and simplify docker workflow

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#808]
It's high time we get Docker figured out. The existing Dockerfile was created in the 0.3 era of postgrest and as written won't work with 0.4. There are more than one way to fix it. In particular there are two PRs currently open (#738, #762), and I appreciate the work that went into them. I'd like to propose a simpler way to use Docker though.

**Proposal**: provide images on Docker Hub for tagged version releases only, remove nightlies, have a "latest" alias for the newest tagged version.

Here's why:

* Docker support is crucial for people deploying postgrest to Kubernetes, but are these people deploying nightlies?
* I would prefer that support requests from Docker users be on a known version. It's easier than debugging a problem in a random build.
* We can avoid complicated build machinery and its maintenance.
* Stack builds postgrest from source reliably on all platforms that I'm aware of, so contributors can already play with the newest build without needing Docker.

Also, for the design of the Dockerfile:

* Continue having the Dockerfile download a binary from the Github releases. I build these binaries anyway, so no extra work there.
* Require mapping in a configuration file rather than accepting env vars. The dockerfiles of nginx and apache do it this way, and postgrest is a web server too so is it that weird?

**Comment by ruslantalpa** [comment]
All except the last point about  env vars.
This is a situation where you can totally have your cake and eat it too :)
start with an image that has the binary and a default conf file and the CMD is postgrest -c /....

then add an entrypoint script that checks if an env var like `POSTGREST_ANON` exists then it does something like 

`echo "anon-user=$POSTGREST_ANON" > /etc/postgrest.conf`

with this way the user will have the option to either bake the config file in, provide it with a mapping or override a specific config parameter using a env var

**Comment by deinspanjer** [comment]
> Proposal: provide images on Docker Hub for tagged version releases only, remove nightlies, have a "latest" alias for the newest tagged version.
 
> Docker support is crucial for people deploying postgrest to Kubernetes, but are these people deploying nightlies?

Only if they are developers contributing to the postgrest project in the context of their own applications.  I think it makes sense to try to make things easy for developers both in and out of the Docker environment.

> I would prefer that support requests from Docker users be on a known version. It's easier than debugging a problem in a random build.

Agreed.

> We can avoid complicated build machinery and its maintenance.

Agreed.

> Stack builds postgrest from source reliably on all platforms that I'm aware of, so contributors can already play with the newest build without needing Docker.

If we don't add the code to stack.yaml to enable building the Docker image, then we expect those contributors who need to test nightlies or their changes within the Docker environment to maintain their own custom Docker build system for taking the built binary and putting it into an image to test.

> Also, for the design of the Dockerfile:
> Continue having the Dockerfile download a binary from the Github releases. I build these binaries anyway, so no extra work there.

In PR #762, the dockerfiles/Dockerfile is basically a minimal shell with dependencies.  It would work just as well with shoving a binary downloaded from releases as with one copied from a build.  If there is any negative to running `stack --docker build` as part of the release process to get the official build, then having the Dockerfile download the binary from releases would be a fine alternative.

> Require mapping in a configuration file rather than accepting env vars. The dockerfiles of nginx and apache do it this way, and postgrest is a web server too so is it that weird?

There are several cases where it is much easier or even better to use environment variables rather than just a config file.  I don't think we should completely eliminate that without careful consideration.

The nginx image documents how to use envsubst to allow using variables in its config file.  This is a viable alternative, but it requires the user to create and maintain a template config file.
The approach in #762 removes the need for a template.  You can either pass in a config file if you have one, or you can use environment variables if you wish.  This functionality is documented in the dockerfiles/postgrest-docker-usage file.


In summary:

- I am fine with focusing on only officially released builds available on hub.docker.com.  Nightlies are right for some projects, but not all by any means.
- I think that accepting the `stack --docker build` functionality of #762 doesn't get in the way of that desired release plan.  It can be used to create the released Docker image, or it can just be left in as a tool for a subset of the contributors.  The additions to stack.yaml look like a lot, but that is just because I put a *lot* of doc comments in there.  It is only 20 or so actual code lines, and reviewing them, the only one that would ever likely need to be touched is the variable for the release version number.
- I think we should consider keeping the postgrest-env wrapper script from #762 as it gives the user more flexibility and it doesn't have to be used if it isn't needed.


@ruslantalpa can you take a look at the dockerfiles/postgrest-docker-usage in #762 and see if it serves the purpose you describe above?

**Comment by ruslantalpa** [comment]
@deinspanjer there is something there but it's much more complicated then i was thinking.
My idea was that on startup entrypoint would look if env vars exist and append their values to the postgrest conf, something very very simple.

**Comment by deinspanjer** [comment]
> @deinspanjer there is something there but it's much more complicated then i was thinking.
> My idea was that on startup entrypoint would look if env vars exist and append their values to the postgrest conf, something very very simple.

@ruslantalpa I don't understand what is off with it.  That is exactly what the postgrest-env script does.  If it finds any of the possible environment variables, it will use them in the postgrest.conf.  The only thing the user has to do is set those variables in their docker-compose file or with -e arguments to `docker run`.

**Comment by ruslantalpa** [comment]
Sorry for the late reply.
If i read that file correctly you have to supply all the config settings using env vars (at least the ones that are mandatory) and after that it creates the config file, I however was saying something else.
Let the base come from a baked in config file, it can be the one provided by postgrest or it can be baked in by the users that create a new image based on the official one and just add their own config file, but, once the image is ready, you should be able to override any config property in that file using an env var when you start the container.

**Comment by deinspanjer** [comment]
I see.  so you want a mode where if there is an existing config file, it will be used but it can also be overridden with any environment variables that are passed in.

That can be added to the postgrest-env wrapper.  Let's see what @begriffs thoughts are about continuing with that PR, and if he is interested, I can make that change.

**Comment by begriffs** [comment]
What about this...

* Bundle a config template in the container at /etc/postgrest.conf
* Include the envsubst command in the container
* Make an entrypoint like
   ```bash
   envsubst < /etc/postgrest.conf | postgrest -
   ```

Then the user can interact with docker in three ways

1. **All environment vars.** Don't map a config file in, rather pass vars like `-e DB_SCHEMA=public` etc.
2. **No environment vars.** Map in a fully specified config file to /etc/postgrest.conf (i.e. no variables to be substituted). Then envsubst is a no-op.
3. **Mixed mode.** Mapping in a config file that has most values hard-coded and the option to pass in a few variables.

**Comment by deinspanjer** [comment]
I'm good with that, especially if the config template becomes a first class citizen in the project where it is maintained over time as new features/config options are added.

If it is agreed that we want to use the rest of #762 and just replace the postgrest-env wrapper with this template file and a simple wrapper that calls envsubst, then I am happy to work on that change in the PR.

**Comment by ruslantalpa** [comment]
@deinspanjer i think this task can (should) be accomplished through the entry point shell script which can look something like this.

```sh
#!/bin/bash

#available config options
config_settings=(
	db-uri
	db-schema
	db-anon-role
	# add the rest
)

for conf in "${config_settings[@]}"; do
	var="POSTGREST_${conf^^/-/_}"
	val="${!var:-}"
	if [ "$val" ]; then
	 	echo "${conf}=${val}" >> /etc/postgrest.conf
	fi
done

exec "$@"
```

if you want to take it over from here ... :)

**Comment by begriffs** [comment]
Hm I see, the config can't have keys with blank values like

```
foo =
```

It doesn't parse. I had hoped the missing value would have the same effect as omitting the `foo` line altogether. So we can't fill in a template config file when any variables are missing because that would leave a blank value and fail to parse.

So Ruslan's script to loop over the available settings is probably the way to go, even though it will require maintenance whenever we add new properties to the config file.

**Comment by ruslantalpa** [comment]
If the default config file woyld contain all settings (live ore commented) the script could be devised to read them from the conf instead of hardcoding them. But i think it's not worth the complication for now

**Comment by deinspanjer** [comment]
The postgrest_env script I currently have parses the config options out of the usage text you get with `postgrest --help`.  It could just as easily parse those out of an official postgrest.conf.dist instead.  I don't think it should parse the option names out of a live /etc/postgrest.conf file though because it may not be in an expected state.  See below.

Once it has a list of the available options, it converts the names to something that looks like an environment variable.

Finally, the current code then builds a config file from each of those env variables that is set.

As I understand it, we want new logic that replaces that last step with the following at a minimum:
* Start with the existing config
* If an environment variable exists which overrides one of the current values in the config, update the config with the value from the environment variable.
* If an environment variable exists which defines a variable for a setting that doesn't exist or is commented out in the config, add a line with the value from the environment variable.
* After processing, run postgres with the possibly modified postgrest.conf.

Here are some questions and possible additional requirements:
* If we want to continue using the `postgrest --help` text as the canonical list, that is fine.  If we don't like that, we should make an official distribution conf file, i.e. postgrest.conf.dist that is maintained with the full list of valid settings so the script can parse that.
* I don't think we can parse the existing /etc/postgrest.conf file for the list of settings because the user might not have all of the available config options in there, commented out or otherwise.
* Do we want to allow the user to unset a config value via the environment? If so, what would the syntax be?
* Do we want to overwrite the starting config file or generate a new file with the overrides and run with that instead?

**Comment by begriffs** [comment]
Check this out, the library we use to parse the config file allows env variables to be interpolated: https://hackage.haskell.org/package/configurator-0.3.0.0/docs/Data-Configurator.html#g:4

That means we don't need envsubst at all, we can do stuff like

```ini
# inside postgrest.conf

db-uri = $(POSTGREST_DB_URI)
```

This would allow us to follow my idea of having a default config in /etc/postgrest.conf that uses environment variables, with the option to map a new config file into the container if desired.

**Comment by deinspanjer** [comment]
This is great, that will definitely make things much easier.

Does that mean that you don't want to consider adding the configuration to stack.yaml to enable building the docker image from the stack command?

**Comment by ruslantalpa** [comment]
I for one have not looked exactly ant what the relationship between docker and stack is but i see one benefit if this is what i think it is.

Currently if you want to build a docker image on something like circle where the base is something else the ubuntu, then you have to have a second "build" image where you build the executable, extract it then add it to the production image using copy. If the need for this "build" image is removed if we do this stack thing, then i am all for it.

**Comment by deinspanjer** [comment]
There is still a build image, but it is a very simple template container that just has the pg dependencies installed so we can copy the resulting build into it rather than having to build from scratch.  Very easy to maintain and explore

**Comment by begriffs** [comment]
Sure, we can include the extra Docker configuration for the stack.yml.

**Comment by begriffs** [comment]
@deinspanjer any progress on your "v2" docker setup in stack.yml?

**Comment by deinspanjer** [comment]
My progress was blocked by PR 826 a couple of weeks ago, and I did not notice that it was merged.

I'm a bit swamped at work at the moment, but I'll try to get the PR updated by this weekend.

**Comment by begriffs** [comment]
Just another friendly reminder about this. If you no longer feel like doing it let me know and I'll stop bugging you -- no pressure! 😁

**Comment by begriffs** [comment]
Well, looks like I can close this issue. If there are particular problems with the docker setup nowadays we can open new issues for them.
