### ISSUE TITLE
Disable escaping of json returned by stored procedures

### ISSUE THREAD

**Issue by fab1an** [begriffs/postgrest#812]
I have a stored procedure that returns `json`, but the output seems to be escaped:

`"{\"mark\": {\"signature\": \"bb\", \"lastIncludedIdx\": 21}}"`

Is there a way to disable this?

**Comment by begriffs** [comment]
Can you share more about your stored procedure including its return type? Perhaps it simply returns a string and postgrest is passing that along.

**Comment by fab1an** [comment]
Sure, thanks for looking into it.

It's still only a test, hence the hard-coded values.

```plpgsql
create function api_view()
returns json as $$
    select to_json(text '{"mark": {"signature": "bb", "lastIncludedIdx": 21}}') 
        union all (select data::json from v_changes limit 10);
$$ language sql strict;
```

**Comment by ruslantalpa** [comment]
to_json is not doing what you think it is doing, what it does here is it gets a string and makes it a valid json value (which is escape the string and enclose it in ").

instead of 
`select to_json(text '{"mark": {"signature": "bb", "lastIncludedIdx": 21}}')`
try this
`select '{"mark": {"signature": "bb", "lastIncludedIdx": 21}}'::json`

**Comment by ruslantalpa** [comment]
You are probably looking for json_build_object https://www.postgresql.org/docs/current/static/functions-json.html

**Comment by fab1an** [comment]
Thanks!
