### ISSUE TITLE
postgrest: Thread killed by Warp's timeout reaper

### ISSUE THREAD

**Issue by eric-brechemier** [begriffs/postgrest#827]
I noticed these strange logs while running PostgREST `master` (0.4.x):

```
postgrest: Thread killed by Warp's timeout reaper
```

I ran PostgREST with:

```
stack exec postgrest ../postgrest-config/localhost.config
```

on macOS Sierra (version 10.12.2).

**Comment by begriffs** [comment]
Thanks for the bug report. Have you noticed whether it messes up responses to client requests? Is it pretty reliable to reproduce the message in the logs?

**Comment by majorcode** [comment]
I can confirm that this message appears in the log output after a minute of inactivity. The server stays running and ready for client requests. Maybe it's normal resource reclamation? It does sound ominous, though.

A quick Google turned up [this](https://github.com/yesodweb/wai/blob/76e335bb76711fe37f548c39435d4870e8575868/warp/Network/Wai/Handler/Warp/Timeout.hs#L114) reference to an exception. Maybe it would be best to suppress the message?

@begriffs This seems to be low-hanging fruit for me to offer my first crack at contributing. Shall I take a look and offer a pull request?

By the way, I was able to get local build working with very little trouble. And the tests run successfully. I researched OpenAPI regarding listing embedded resources on the root path output. I have many opinions about OpenAPI that I will discuss elsewhere. Otherwise I'm ready to rock.

**Comment by begriffs** [comment]
Sounds like a great contribution to me! Give it a try and feel free to open a pull request with ideas even if it's not totally done yet. We can talk about the problem there as needed. Glad the local build was smooth and tests are passing.

**Comment by eric-brechemier** [comment]
@begriffs I am using 3.0.2, not 4.x day to day; I just started 4.x a few times and got the error each time after a few minutes, which is in line with @majorcode's analysis.

**Comment by majorcode** [comment]
@eric-brechemier Can you tell me what tool you used to make your requests to PostgREST?

I get the message, after a delay, when using Chrome or Postman. But the message isn't printed when I use `curl` or `wrk` on the command line. I suspect that browsers leave the connection open too long and the server kills the thread--probably for some Slow Loris defense.

**Comment by eric-brechemier** [comment]
@majorcode I used Postman to post requests.
