### ISSUE TITLE
provide RESTful routes to single resources via primary key

### ISSUE THREAD

**Issue by reece** [begriffs/postgrest#830]
See also: #235, https://postgrest.com/en/v0.4/api.html#singular-or-plural

I understand the arguments for array-based replies and I appreciate the generality of a query syntax that enables multi-column keys. I also appreciate the desire for there to be one way to do things.

However, it is extremely common for REST URLs to include the "primary key" as a component of the query path. To not provide this in postgrest denies the most common usage pattern in favor of theoretical corner cases. (I write this as a person who often focuses on exceptions!)

**There is an important shortcoming of the current approach: missing resources do not return errors.** With the current query argument approach, filtering is searching; valid searches always return status 200, even when results are empty. By comparison, an equivalent request for a specific resource (via PK in the path) would return 404.  That is, query paths like `/table/somekey` are NOT the same as `/table?pk=eq.somekey`.

Proposal: All tables with single-column primary keys have *additional* routes of the form `/table/<pk>` that returns a single resource and 200 if it exists, or 404 if not.

Thanks for Postgrest... it's awesome!

**Comment by begriffs** [comment]
Actually if you use the request header `Accept: application/vnd.pgrst.object+json` it will behave with the 404 not found semantics when the ordinary request would have returned an empty array. Sorry for not documenting that as clearly as I should have. The idea is that allowing manual control over the "singular resource" semantics with a header allows you to apply it both where a url convention would have done it before, and also for stored procedures.

You might be interested in #825 which links to an nginx helper to automate the URL syntactical sugar.

**Comment by reece** [comment]
@begriffs Thanks for request header and nginx tips. I'm not running nginx already, so I'd like to avoid that rabbit hole.

It seems to me that this simple, common use case should work out of the box, and I'd love to help make that happen. From reading #825, I think you sound open to the idea of embedding this syntactic sugar into postgrest itself (perhaps as an option). Is that correct?

I've scanned the code, but I'm kinda lost in haskell, so I can't commit to a PR.

**Comment by begriffs** [comment]
I researched how to do it in nginx and added code for you in https://postgrest.com/en/v0.4/admin.html#alternate-url-structure

I realize you don't want to add the complication of a reverse-proxy, but if you're going into production with postgrest you'll probably want nginx for other reasons like HTTPS support.

Ultimately I'm not against provide the URL shortcut in postgrest because a lot of people ask for it. However doing it right will involve some careful work. The code will have to check whether the table in question has a simple primary key, and what the column is in order to rewrite the query. If there is a compound primary key (or no key at all) it should return the right error code. Also the shortcut probably can't work for views or stored procedures.

**Comment by begriffs** [comment]
Another note about proper implementation is that other filtering options should probably be disallowed for `/foo/:id` while embedding options should continue to work.

**Comment by ruslantalpa** [comment]
and another not is that this should return an object directly and not an array with a singe object

**Comment by begriffs** [comment]
Just following up on this issue.

1. The feature involves a fair bit of work.
2. The functionality is already there with the right client behavior.

I'm not philosophically opposed to it, but also not personally motivated to work on it. However if this issue is important enough that an organization would sponsor the development then we could talk about that option.

**Comment by ruslantalpa** [comment]
closing this since it's been a while, it's o priority since there is a way to implement this feature with nginx or the client making the correct request.

As @begriffs if someone really needs this in PostgREST, please reopen the issue with suggestions.
