### ISSUE TITLE
customization

### ISSUE THREAD

**Issue by MannusEtten** [begriffs/postgrest#833]
i can't read anything about customization of the api.

I can imagine that for certain calls there needs to be done some extra stuff. Hence our own requirements. We have to store some data into the database so this rest api is wonderful but after we added the data into the database we have to give this data also to some other tool for processing.

**Comment by ruslantalpa** [comment]
That is done with a combination of proxy,triggers,listen/notify events,   depending on the specifics of the thing you are trying to accomplish.

**Comment by begriffs** [comment]
@MannusEtten as Ruslan said, you can process data with an external program by using PostgreSQL's [LISTEN/NOTIFY](https://www.postgresql.org/docs/9.6/static/sql-notify.html). When you have new data to be processed, you can send a NOTIFY (this can be automated using a trigger on a table for instance so that newly inserted rows automatically get processed).

External programs can either directly LISTEN to the database, or you can bridge the NOTIFY events into a robust worker queue with one of these programs:
https://postgrest.com/en/v0.4/intro.html#external-notification

**Comment by ruslantalpa** [comment]
Some example of how to do extra stuff https://github.com/subzerocloud/postgrest-starter-kit/wiki/Beyond-Data-Access
