### ISSUE TITLE
Provide Alpine Docker image

### ISSUE THREAD

**Issue by mcarans** [begriffs/postgrest#867]
It would be good to have an Alpine Docker image. I have created one here:
https://hub.docker.com/r/mcarans/alpine-haskell-postgrest/ which uses the last version of Postgrest that worked with Alpine 3.4.
(Git commit hash: 726b2b9d18a3b8217d83c514122560fd5f71af95)

It can be used in docker-compose.yml like this:
  rest:
    image: mcarans/alpine-haskell-postgrest
    ports:
      - "3000:3000"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
    command: ["sh", "/root/runpostgrest.sh"]
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"

**Comment by begriffs** [comment]
Thanks for putting that together. Can you try making some API requests to it and leaving it running for a while? Last time we experimented with Alpine we ran into a GHC memory leak that appears to be related to that platform.

**Comment by ruslantalpa** [comment]
@mcarans it's not about leaving it for a while, you need to send a lot of requests to PostgREST to use up some memory so that GC has something to clean up. You need to generate like upwords of 1M requests in a short time frame (5-10min). Watch the memory used at the beginning, see it grow during the test. If it the end, the memory usage goes down to the initial level, you are fine but i think it will stay up (this is what i saw when i did this test in the past, didn't feel like tracking this down since alpine is not an officially supported platform of GHC, and the bug seems to be a  very low level)

**Comment by mcarans** [comment]
Ok maybe you can make an Alpine Postgrest image available (or point to mine as an unofficial one) with a warning that millions of requests per minute has been known to cause a memory leak (as Alpine is not a supported platform for GHC) so people can choose to use it or not given the warning.

**Comment by ruslantalpa** [comment]
the problem does not appear ONLY when you have a big rps number. The problem is that used memory does not get cleaned up at any volume. whatever your load, eventually your server is going to run out of memory and crash. The 1m number was just a way for you to flash out the bug in a short timespan (5min). Unless this is fixed i would not suggest to anyone to use alpine with postgrest in any setting. This is a fundamental bug that can have weird manifestations so i would not want ppl submitting bugs like "postgrest crashed/uses a lot of memory" and finding out 2 days into debuging that he is using an alpine image

**Comment by mcarans** [comment]
Ok fair enough. I will let you know how things go with leaving my Postgrest running. Do you recall what Alpine version you tested before? The image I created is for 3.4.

**Comment by just1689** [comment]
@mcarans Any news?

**Comment by mcarans** [comment]
It seems to be stable for me - no issues - but then it is not receiving that many requests, certainly not the millions per minute necessary to surface the bug.

**Comment by danilobuerger** [comment]
@mcarans Could you please provide an up to date Dockerfile thats using ghc from testing?

**Comment by mcarans** [comment]
```
FROM unocha/alpine-base:latest

MAINTAINER XXX <XXX@XXX.com>

RUN echo "https://s3-us-west-2.amazonaws.com/alpine-ghc/7.10" >> /etc/apk/repositories && \
    curl -so /root/runpostgrest.sh \
        https://raw.githubusercontent.com/OCHA-DAP/alpine-haskell-postgrest/master/runpostgrest.sh && \
    curl -so /etc/apk/keys/mitch.tishmack@gmail.com-55881c97.rsa.pub \
        https://raw.githubusercontent.com/mitchty/alpine-ghc/master/mitch.tishmack%40gmail.com-55881c97.rsa.pub && \
    apk add --no-cache --update build-base git xz postgresql-dev ghc stack && \
    git clone https://github.com/begriffs/postgrest.git --single-branch && \
    cd postgrest && \
    git checkout 726b2b9d18a3b8217d83c514122560fd5f71af95 && \
    stack build --copy-bins --local-bin-path /usr/local/bin && \
    stack clean --full && \
    cd .. && \
    rm -rf postgrest && \
    apk del build-base git xz postgresql-dev ghc stack && \
    apk add --no-cache libpq gmp && \
    rm -r /root/.stack && \
    rm -rf /var/lib/apk/*

CMD ["postgrest", "$DB_URL", "-a", "XXX"]
```

Replace XXX above appropriately. Note that I wanted to use one of our org's base images and so was restricted to a non-current version of Alpine, hence the checkout of a specific commit, the last to support the Alpine version.

**Comment by ruslantalpa** [comment]
we now have an automated release script. you could add a PR to build the alpine specific binary and docker.

**Comment by ruslantalpa** [comment]
a PR would be welcomed.
