### ISSUE TITLE
Complex boolean logic doesn't accept 3 clauses

### ISSUE THREAD

**Issue by priyank-purohit** [begriffs/postgrest#889]
Can't do `or=(cond1, cond2, and(cond3, cond4))`. It must be two clauses at a time` or=(cond1, or(cond2, and(cond3, cond4)))`. Is this is a purposeful limitation?

**Comment by steve-chavez** [comment]
Purpose of that was mostly keeping the and/or feature simple since it changed a lot of code, I realize now that it can be cumbersome to do that kind of expressions, I'll see if I can improve the expressiveness of the interface; @begriffs maybe you can label this as enhancement and I'll work on it when I have the time.

**Comment by priyank-purohit** [comment]
@begriffs It would be better to release v0.4.3.0 with this merge before the docs are updated for v0.4.2.0. Otherwise it'll just be 2x the work.

**Comment by begriffs** [comment]
Yep, I'll apply your docs pr to 4.3 when that version is released and available on docs.
