### ISSUE TITLE
Caching Data (ex: post categories)

### ISSUE THREAD

**Issue by ACPK** [begriffs/postgrest#893]
When using PostgREST, how would I go about caching the data? Due to the amount of categories (8,000), it can take awhile for the PostgREST endpoint to finish loading.

**Comment by ruslantalpa** [comment]
8k records is no big deal for the db/postgrest (unless there are a lot of columns and json encoding takes time). I think your problem is that it takes a while to send that data over the network so in this case, cache on the server side won't help.
But to answer your question, you would cache the response in front of postgrest using the proxy (nginx/openresty)

**Comment by begriffs** [comment]
You bring up a good point. I'm searching for the issue but can't find it...perhaps I never made an issue for this.

Postgrest currently doesn't provide a way to add http caching response headers. A workaround is to add them for certain routes with nginx on top of your server.

In the long run we could consider having a separate metadata table like this:

```sql
create table cache_lookup (
  relation regclass primary key,
  etag regproc,
  max_age regproc,
  last_modified regproc
);
```

When a request comes in postgrest would check if there's a matching relation in cache_lookup for the table/view specified by the client. If it finds a row and any of the other columns are not NULL, postgrest would call the stored procedures they reference to obtain values for those headers.

**Comment by ruslantalpa** [comment]
I was able to implement caching with custom logic in nginx using a combination of
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_path
and
https://github.com/cloudflare/lua-upstream-cache-nginx-module
