### ISSUE TITLE
highly available / load balanced / clustered pg configurations 

### ISSUE THREAD

**Issue by priley86** [begriffs/postgrest#903]
are there any documents describing how one might configure postgREST to work in a highly available environment? It seems like this would be a nice addition to the current documentation.

I.e. suggested practices & configurations which might allow the following:
https://wiki.postgresql.org/wiki/Replication,_Clustering,_and_Connection_Pooling

If this exists, please link me :)

thanks for this amazing project.

**Comment by ruslantalpa** [comment]
@priley86 PostgREST is a stateless* application, thus you can run as many as you like in parallel.
You can have nginx in front of them for loadbalancing or an AWS LB.
Probably an easier way to manage multiple parallel versions is through containers on AWS ECS, we are moving in this direction here https://github.com/subzerocloud/postgrest-starter-kit/tree/master/cloudformation
Running multiple instances is parallel i would say is for availablity mostly since since PostgREST can handle a lot of traffic so you should only look at 2-3 instances in parallel.

On the other hand, documenting how to make the database itself highly available and scalable is not this projects's job :) it's a complex thing to undertake, but i would caution about overengenerent in this area (db availability and scale) especially in the beginning of the project, go with RDS and don't waste your time solving problems you don't have ( and probably [never will](http://akorotkov.github.io/blog/2016/05/09/scalability-towards-millions-tps/))  

*=postgrest caches the database schema and needs a HUP (for now) when you change it (the sechema).

**Comment by begriffs** [comment]
I'll also note that postgrest uses read-only transactions when possible so that queries can be run on read replicas of the database. (Original discussion in #547)

**Comment by priley86** [comment]
@ruslantalpa i noticed this CloudFormation template. thanks very much for sharing this (I may end up collaborating w/ you there) - also a huge plus for Graph QL. AWS RDS is great until you start to scale (and then vertical scaling can become quite expensive). For that reason, I prefer the horizontal path (although seeing these numbers on vertical capabilities is quite encouraging). I will need to monitor my performance and get back with you on this topic...

@begriffs appreciate this. A read replica will be great for anything static (non changing). I'll make that optimization sooner than later. I guess a better question would be, how would you approach horizontal partitions/shard keys, etc.? Is there anything that can be done at this point towards a horizontal path?

**Comment by priley86** [comment]
@ruslantalpa can you elaborate on how your parallel ec2 instances share storage? This seems to be a good option...I should add, I have done a lot of research in the area of ec2/kubernetes recently, and it can become quite expensive running these configurations. Scaling w/ something more affordable in mind up front is a personal goal...

**Comment by begriffs** [comment]
@priley86 sharding strategy depends on your use case. Are you making a a multi-tenant app where each tenant could get its own resources?

**Comment by priley86** [comment]
@begriffs single tenant. single app purposes here. just want the ability to scale horizontally and affordably.

**Comment by ruslantalpa** [comment]
@priley86 horizontal scaling https://www.citusdata.com/ that's  the best  solution i have seen
You can share a EFS if you want but postgrest does not need storage.

the ECS cluster has an autoscaling group linked with a launch configuration. and in that launch configuration, you do

```
#cloud-config
package_upgrade: true
packages:
- nfs-utils
runcmd:
- mkdir -p /var/www/html/efs-mount-point/
- chown ec2-user:ec2-user /var/www/html/efs-mount-point/
- echo "file-system-id.efs.aws-region.amazonaws.com:/ /var/www/html/efs-mount-point nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0" >> /etc/fstab
- mount -a -t nfs4
```

http://docs.aws.amazon.com/efs/latest/ug/mount-fs-auto-mount-onreboot.html

**Comment by priley86** [comment]
@ruslantalpa thanks a lot for all the advice here. I will try this out soon.

**Comment by begriffs** [comment]
We'll have to double-check whether postgrest is compatible with Citus. Postgrest uses CTEs in its queries which can prove difficult with Citus when the queries need information from multiple shards. If you were using postgrest in a multi-tenant manner then the entire query could be "pushed down" to a single node in the distributed database because all the tenant specific data could be stored in one place.

It would be worth pointing postgrest at a citus cluster and seeing what kind of errors we might get, and whether there are adjustments to the postgrest auto-generated queries that would make the two more compatible for a greater number of use cases.

**Comment by ruslantalpa** [comment]
The original question seems answered (to an extent) if there is a follow-up, please reopen

**Comment by patrickmichalina** [comment]
With the release of bi-directional replication in pg16 would that be a way to easily scale PostgREST?
