### ISSUE TITLE
Cross-schema joins?

### ISSUE THREAD

**Issue by dthree** [begriffs/postgrest#921]
It does appear that you can only specify one schema per instance of Postgrest.

Is there at least any way to join across schemas?

I would really like to use Postgrest on a large project, however this database has over 10 schemas that all need to talk to each other. Collapsing to a single schema isn't an option.

**Comment by begriffs** [comment]
You can make views in one schema that select values in an underlying table in another, but that would quickly become cumbersome. Can you explain why you have so many schemas? Is it for multi-tenancy?

**Comment by dthree** [comment]
Thanks for the faster answer!

Let's say I want to store data on:

 - HR
 - Users
 - Finance
 - Customer

These are very separate and will span hundreds of tables. However, they do very much need to cross-reference.

Perhaps I just have had the idea that it's bad practice to bunch them all together. I could be wrong. 

Your thoughts on the matter would be appreciated!

**Comment by ruslantalpa** [comment]
If you configure PostgREST with `db-schema = ""`than the generated query will not be schema qualified, so the usual search path mechanism will apply, thus allowing you to work with any table/view with the condition that the names in different schemas do not clash (or search_path somehow takes care of that).

While it's possible to do this, I would not recommend it since you can no longer have the easy mental model of "whatever is in `api` schema is potentially HTTP accessible", now you need to worry about the privileges for each and every table and be much more careful.

**Comment by dthree** [comment]
You solved this for me, by suggesting I use a schema that solely consists of views.
