### ISSUE TITLE
Transitive embedding with composite FK

### ISSUE THREAD

**Issue by 9too** [begriffs/postgrest#928]
Consider a case of a [weak entity](https://en.wikipedia.org/wiki/Weak_entity)
```sql
create table a  ( id int primary key, value text );
create table b  ( id int primary key );
create table a_b ( a int references a, b int references b, primary key (a,b) );
create table ab ( a int, b int, attribute text, foreign key (a,b) references a_b );
```

It is currently impossible to request transitive embedding
```
GET /ab?select=a(value)
```

It is possible to declare it explicitly 
```
GET /ab?select=a_b(*,a(*))
GET /ab?select=a_b(a_id,b_id,a(a_id,value))
```
But it gets quickly out of hands if you add more levels, and you must at least specify the full FK in the intermediate table (_i.e._ a_b)

The easy workaround is to simply add a direct FK on the weak entity, which is definetly not a headache.

**Comment by ruslantalpa** [comment]
I think when you say "impossible" you actually mean you encountered an error
that is because ab is related to a in 2 diffrent ways, and where (was) no way to say which link to use, but that got added by this PR https://github.com/begriffs/postgrest/pull/918
which is in master but unreleased yet. i think this is what you are looking for.

I'll close, please reopen if that does not solve your case
