### ISSUE TITLE
where is the "hypermedia" or "hateoas" word ?

### ISSUE THREAD

**Issue by docteurklein** [begriffs/postgrest#941]
Hey there :)

Sorry to bother you with an [already discussed](https://github.com/begriffs/postgrest/search?q=hypermedia&type=Issues) subject, but I think this is important.

I think those discussions miss one important part of what makes REST successful: **discoverability**.
The `OPTIONS` support [(lack of)](https://github.com/begriffs/postgrest/issues/790)  is only a small stone of the whole hypermedia thing, but auto-discoverability is what makes the internet still working.

Client implementors shouldn't have to look at an (open-api) spec and then hardcode URL patterns all over the place. json-ld or hal+json (or any other hypermedia format, like html f.e) is [not just about `@id`](https://github.com/begriffs/postgrest/issues/343#issuecomment-173767731).
Hypermedia is what makes REST interesting in the first place. 

Is there any pointer on how I could implement such a thing using postgrest?

Thanks!

**Comment by ruslantalpa** [comment]
@docteurklein can you show a client that takes advantage of this "autodiscovery" thing and does something interesting besides things like swagger-ui?

**Comment by docteurklein** [comment]
Thanks for the quick answer!
Forgot to tell I'm totally new to postgrest, but I find the idea amazing. Also discovering the existence of a gitter chat room, maybe I should have started with that.

back to the question:

- I would try to generate (relative?) URLs pointing to associated resources directly inside the returned representation (using `_links` with json-hal) or json-ld context) instead of embeeding it
- attach context to representations using schema.org types so that a client **discover** it's a date field (or an age or an email or a phone number f.e)
- restore OPTIONS to discover available operations on a given resource (tho this could be handled by json-ld+hydra operations)

An example of such a client discovering resources and generating a web UI out of it would be http://api.opensupporter.org/hb2/browser.html#http://api.opensupporter.org/api/v1/questions
(the hal browser).

**Comment by docteurklein** [comment]
same kind of browser but with json-ld  + hydra: http://www.markus-lanthaler.com/hydra/console/?url=http://www.markus-lanthaler.com/hydra/event-api/

**Comment by ruslantalpa** [comment]
The example you gave is still something like swagger-ui which is basically a form of documentation.

Ppl say "autodiscovery" and "how the web works" like in "if this feature was available, magic things would happen and clients would suddenly become sentient and start crawling the open APIs without developer telling them what to do" but it is never so, ultimately it's still a human clicking those links and navigating the api, not the "client/code".

@docteurklein what is your actual use-case for this? If it's just so you can hook up things like swagger ui and hal to postgrest i am not convinced :), these types of things to me sound more like "look at this cool thing I did with my api, no coding required" than actually a feature that is essential to serve the end client/human/non-developer/business need. I'd rather see everyone working on features that are used in production (still a long list of useful things that can be done, like complex mutations) rather than these /side/nice to have/developer ego stroking/ things :)

any thoughts from other ppl, what are other use-cases for this that I am not seeing?

**Comment by ruslantalpa** [comment]
a note on my previous comment. Side things that help developer to work with apis are of course important even if they don't run in production and an example of such a tool is GraphiQL but i've not seen such a good quality tool for the REST world. Even if there was such a thing, GraphiQL is still driven by what is essentially a static JSON file for which you don't need any special features in postgrest, you just point that tool to that static file.

**Comment by docteurklein** [comment]
My main motivation is more conceptual indeed. I'm convinced that maintenability and evolutability of RESTful APIs is rooted in correctly following [REST principles](https://martinfowler.com/articles/richardsonMaturityModel.html)  and that open-api specs is a bad idea (or as good as WSDL was with SOAP).

Hardcoded clients are mainly the reason why we need server-side versioning.
Now I fully agree with you that the [semantic gap](https://youtu.be/UkAt9XSOfaE?t=2883) implies humans have to read the docs and think what to consume and make sense of the it, but once client and server side tooling improves it could greatly simplify client-side developers life, without them having to hardcode everything.

I agree that the tendency is to move to WSDL-like formats, and that it seems like a productive method.
I can't stop to think however that because it's easy to bootstrap does not mean it's good in the long term.

**Comment by docteurklein** [comment]
Another really concrete reason why we need to push more around those concepts is the recent trend of graphQL replacing RESTful APIs. It either means REST is bad or that it misses something.

**Comment by ruslantalpa** [comment]
Probably my biggest argument against implementing this (besides it not being actually useful beyond documentation and developer tooling) is that it can be implemented using the features already present as I've explained [here](https://github.com/begriffs/postgrest/issues/13#issuecomment-319890673) and [here](https://github.com/begriffs/postgrest/issues/343#issuecomment-154342755)

I'll close this for now since I don't see it going further any time soon but if you disagree and have other arguments, it can be reopened

**Comment by docteurklein** [comment]
thanks for the pointers. I'll try it!

**Comment by conormuldoon** [comment]
Hypermedia is useful for more than documentation and developer tooling. It’s useful when your API, like the Internet, must be capable operating across organisational and national boundaries. In such cases, the URIs discovered using hypermedia with be different depending on where the API is being accessed from and the proxies requests are being forwarded through. It’s fine for your system to not support hypermedia, but don’t call it RESTful. Hypermedia is a key feature of REST.

**Comment by steve-chavez** [comment]
@conormuldoon I would be interested in exploring more about hypermedia/hateoas in PostgREST, do you have suggestions to move us forward in this regard? What could we improve about our REST interface?

You could open a new issue or discussion to have a fresher start.

**Comment by conormuldoon** [comment]
@steve-chavez I’m not familiar with how your system is implemented, but it might be worthwhile to investigate if it is possible to automatically generate hal/hateoas descriptions for the APIs. X-Forwarded-Proto, X-Forwarded-Host, and X-Forwarded-Port headers from proxy servers could be used to generate URIs for clients accessing the APIs from different locations or through different proxies.

**Comment by steve-chavez** [comment]
FYI, we're restarting discussion on HATEOAS on https://github.com/PostgREST/postgrest/issues/2579
