### ISSUE TITLE
Option to serve index.html from DB

### ISSUE THREAD

**Issue by fab1an** [begriffs/postgrest#950]
Minor suggestion from this issue: #190

If `postgrest` could be configured to serve *only* index.html  for`GET /` from a view in the database, many users could spare running an extra webserver.

Benefits:
* Single-page-apps are possible (javascript and images can be easily inlined nowadays, client-side hash-based routing is also a thing).
* No file-access or routing-logic necessary
* Everything still is in the database

**Comment by ruslantalpa** [comment]
**In regard to this particular request:**
`/` is reserved for openapi, having a configuration change the route behaviour would be an inconsistency.

One could probably create a RPC that responds with `HTML` and the only thing needed in postgrest would be to reply with a different content-type header and it should work. 

There is a desire to have a feature where an RPC could control  the reply headers #940 and if that is done, then you probably can have this exact feature that you want, but under a path like `/rpc/index`



**As a general thought:**
I frankly do not understand "it's too complicated to run an extra webserver" thinking/logic.
With docker it's basically one config with 10 lines and 1 command, why do we need to put effort into this just to have 1 small feature that is anyway useful only in development since in production you have to use nginx in front if postgrest (see the starter kit that has everything together and it's just one command to bring up, and you can have a html file placed directly there).

i understand the upside of it, if ppl are trying to use postgrest strictly for prototyping but personally, i am not interested in developing features for that use-case (nor would i want to have extra logic sitting in production deployments that will never be executed).

I'll close this for now since I think I explained how this could potentially be implemented and there is a separate issue tracking that feature. 
But you/ppl can reply to this issue with thought about your use-case and why this is important for you and also arguments for developing features in postgrest that are designed for prototyping and not for production (although i really dislike that direction :), postgrest as a tool for prototyping)

**Comment by fab1an** [comment]
I agree that you shouldn't break OpenAPI compliance for this.

It's not only useful for prototyping. In small business there are many many
projects that only ever see 5-50 users, you don't need nginx for that.

Docker config is already too complex for such users. More complex than
having one binary + one config file on a machine.

**Comment by ryanfmurphy** [comment]
Hi @ruslantalpa, I agree with @fab1an that there is something to be said for the simplicity of the single web server, and docker is overkill for what some people want to do.

Besides, it's pretty sweet having a fast webserver in Haskell that's specially designed to talk well/fast with Postgres!  It's a shame to necessarily have to tell Nginx how to do a similar connection to Postgres on the side just so you can serve a slightly different type of response / headers.  I get that it's not that complicated though.  Also I understand the value in keeping this tool simple, don't want to clutter it with extra crap.

For me, I wanted to use an RPC that receives the GET/POST variables, and then be able to use plPGsql as a backend-templating language (a la PHP) to generate HTML/CSS/Javascript.  RPC is so close to this, yet so far away.  Inexperienced at Haskell but I would be willing try to add the feature, though I suspect/respect it needs to be done "the right way" to keep things tight.

Thanks guys!

**Comment by begriffs** [comment]
Wanted to mention that there is a PR now that allows setting custom headers from a stored proc, so that proc could now mark its contents as `Content-Type: text/html` for clients. https://github.com/begriffs/postgrest/pull/986

**Comment by ryanfmurphy** [comment]
Great, thanks for mentioning that @begriffs!  Looks like what I'm looking for.
