### ISSUE TITLE
No information refresh

### ISSUE THREAD

**Issue by jsvalgonc** [begriffs/postgrest#951]
I'm installing the Catarse application ( https://github.com/catarse/catarse) in Cloud 9 development environment and I'm having a refresh problem with Postgrest.   
 
I update the database table(countries) . I select the data and I confirm that it had change.

Then I make a call to that the Postgrest API for that table ("\countries"). 

I have already check my conf file and this connected to the right database.

How can this happen? Is their any configuration or update missing?

Best Regards,

João Gonçalves

**Comment by ruslantalpa** [comment]
Postgrest does not do any caching, is there some kind of transparent proxy in in cloud9?

try using something liek postman, and for each request, try have ing a custom random header like `X-Random-Header: 234234`  and see if somehow making each request unique makes the proxy behave

i am not familiar with could9 but one more thing you could check is to make sure that each request that you make actaully makes it all the way to postgrest but looking at the logs/output of the process. my feeling si that whenever you see an old version of the output (no new records), that request was intercepted and served by a proxy.

to amke absolutly sure, we are talking about changing data in tables, not changing the db schema, because postgrest acttually caches the structure of the database

**Comment by bensweeney** [comment]
did you ever get your catarse to work in cloud 9 just curious?
