### ISSUE TITLE
Multiple Databases

### ISSUE THREAD

**Issue by ACPK** [begriffs/postgrest#958]
Is it possible to connect multiple PostgreSQL databases to one Postgrest server?

**Comment by ruslantalpa** [comment]
No, and that is because postgrest is the wrong place to implement this.

The way to do it is to have postgresql/postgrest pairs (on different ports) and then put a reverse proxy in front (nginx) and do the routing there.

It's far more flexible the then postgrest could ever be if it implemented this.

**Comment by ACPK** [comment]
@ruslantalpa - Thanks for the quick response! Do you have an example of what the reserve proxy would look like?

**Comment by ruslantalpa** [comment]
https://postgrest.com/en/v4.1/admin.html#hardening-postgrest

https://github.com/subzerocloud/postgrest-starter-kit/blob/master/openresty/nginx/conf/includes/http/server/locations/internal_rest.conf
