### ISSUE TITLE
Heroku database rather than RDS

### ISSUE THREAD

**Issue by ACPK** [begriffs/postgrest#959]
Has anyone found a way to use Postgrest with a Heroku PostgreSQL database?

**Comment by ruslantalpa** [comment]
Postgrest uses database roles to manage access/security and since heroku does not allow multiple users https://devcenter.heroku.com/articles/heroku-postgresql#connection-permissions if you expose it directly with postgrest, api users will have the same level of access as your db admin users, i.e. not possible, unless you put some kind of proxy in front and manage the security yourself.

PS: this issue and the other one you submitted are more like questions then issues which is probably best to submit in the chat room https://gitter.im/begriffs/postgrest

**Comment by ACPK** [comment]
@ruslantalpa - How often do people search Gitter's history? I've always used Github issues, even for questions, as I always try to search the Github repo for the answer before asking a question.

**Comment by ruslantalpa** [comment]
i'm not sure, maybe you are right, there is no hard rule/correct way.
My comment was more based on this logic (although not necessarily correct)

- since it's neither an issue/bug/feature request, it's more of a question on how to do a certain thing, as such, the task/question is not very well defined, so it's more of an exploration, a situation where a interactive discussion is better.
- managing issues (although relatively easy) is still a small chore and exploratory questions like this imo add a bit of clutter, though i agree that some times, having them here might prevent the same question popping up again ... so ... i don't know :)

maybe take my previous comment as an alternative to issues.

**Comment by ACPK** [comment]
@ruslantalpa - Traditionally, I see Github issues (as it is an issue for the person posting it as explained by one of my friends at Github) are labeled as questions, bugs, features, etc. Maybe there's a tool to automate that step.

**Comment by begriffs** [comment]
By the way, I think that the Heroku database now allows you to create multiple roles. 

> Postgres manages database access permissions using the concept of roles. Heroku Postgres provides a management layer around these roles called credentials. Each credential corresponds to a different Postgres role and has a distinct set of database permissions.

https://devcenter.heroku.com/articles/heroku-postgresql-credentials

This might make Heroku pg as feasible as RDS for postgrest apis.
