### ISSUE TITLE
Middleware-level data encryption

### ISSUE THREAD

**Issue by titomarifrancis** [begriffs/postgrest#979]
With PostgREST encrypting data before it is written to and decrypting data read from the database, the data in the database is secured even from the DBA for confidentiality. The encryption/decryption key can be part of the PostgREST configuration.

**Comment by ruslantalpa** [comment]
for now there is no near future plan for this especially since this is a very very edge case of working with the database.

I can see this asa way to encrypt passwords that end up in the database (and you can encrypt them before they reach postgrest at the proxy level) but to encrypt every single field, i don't see the point in that mainly because i do not see how one would use the database (write queries against the dataset) if the database itself has no idea what it's storring.

You say you want to "hide stuff" from the DBA, if you are in this situation (not trusting a DBA) your problem is not technology, and if you do not trust your dba, where does it get you since you have to trust your devops team which has access to encryption keys and the login to the db so they can get to the info in the db and decrypt it ...
