### ISSUE TITLE
PostgREST not switching to the database role of the JWT role claim

### ISSUE THREAD

**Issue by barbalex** [begriffs/postgrest#985]
Sorry for bugging as this is most likely just me getting everything wrong :-(

I tried to follow the auth documentation (https://postgrest.com/en/v4.3/auth.html).

Result:

- the post to /rpc/login returns a valid token that contains everything I wanted to have in it (tested on https://jwt.io) :-)
- when I use `db-anon-role = "anon"` in `postgrest.conf`, the next call to the api after posting the login returns a `401 Unauthorized` :-(
- if I use `db-anon-role = "postgres"` or a user with sufficient rights everything works

After hours of trying to get it work I ran this:

    ALTER TABLE ONLY apflora.popber ALTER COLUMN "MutWer" SET DEFAULT current_setting('request.jwt.claim.role');

When I now insert a new row in to table apflora.popber after logging in with one of the way to powerful db-anon-roles - for instance "postgres" - this exact role is written into column "MutWer". Which is not what I expected, after reading:

> When a request contains a valid JWT with a role claim PostgREST will switch to the database role with that name for the duration of the HTTP request.

So it seems to me that the database role was not switched.

I _did_ grant the role specified in the jwt claim to authenticator, plus the group role that really empowers this user.

Maybe my problems have to do with one thing I could not find out after a lot of researching: How should I declare what role is the authenticator role to postgrest? I tried using `db-authenticator-role = "authenticator"` in `postgrest.conf`. But maybe that is not necessary or even wrong?

**Some information:**

- PostgreSQL is v9.6
- postgrest is v0.4.3.0

postgrest.conf is:

    db-uri = "postgres://postgres:secret@localhost/apflora"
    db-schema = "apflora"
    db-anon-role = "anon"
    db-authenticator-role = "authenticator"
    server-port = 4001
    jwt-secret = "another_secret"

The user trying to log in is `z`. This user's role was created like this:

    create role z with login password 'z' in group apflora_artverantwortlich, anon;

role `apflora_artverantwortlich` was created like this:

    revoke connect on database apflora from public;
    grant connect on database apflora to apflora_artverantwortlich;
    grant all on all tables in schema apflora to apflora_artverantwortlich;
    grant all on schema apflora to apflora_artverantwortlich;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA apflora TO apflora_artverantwortlich;
    alter default privileges for role apflora_artverantwortlich in schema apflora
      grant all on tables to apflora_artverantwortlich;
    alter default privileges in schema apflora
      grant all on sequences to apflora_artverantwortlich;

This is the code that does what the auth documentation (https://postgrest.com/en/v4.3/auth.html) explains: https://github.com/barbalex/apf2/blob/master/sql/basic_auth/create_tables.sql

**Comment by ruslantalpa** [comment]
in the docs we call it `authenticator` role because it's the role with which postgrest authenticates itself to the db, hence, that role is defined in the connection string `db-uri`

never use with postgrest a `superuser` role like `postgres`, you need to create a separate role which does not have any privileges

although this is a docker based setup, you can still look at how things are setup, so, here you have the aproximate settings in the config file
https://github.com/subzerocloud/postgrest-starter-kit/blob/master/docker-compose.yml#L40-L47

the values come from here https://github.com/subzerocloud/postgrest-starter-kit/blob/master/.env

now look at how those database roles are created here, including the authenticator role, anonymous, and a custom role called webuser

https://github.com/subzerocloud/postgrest-starter-kit/blob/master/db/src/authorization/roles.sql

notice how the authenticator role does not have any privileges at all except the privilege to switch to other roles like it's done here
https://github.com/subzerocloud/postgrest-starter-kit/blob/master/db/src/authorization/roles.sql#L17

**Comment by barbalex** [comment]
thanks a lot for helping

I changed `postggrest.conf` now to:

    db-uri = "postgres://authenticator:authenticator_secret@localhost:5432/apflora"
    db-schema = "apflora"
    db-anon-role = "anon"
    server-port = 4001
    jwt-secret = "jwt_secret"

And have these roles (ignore the ones prefixed with org_ - they stem from a different database):
![roles](https://user-images.githubusercontent.com/669783/30828504-276cfcfa-a23e-11e7-9103-f66b04638496.png)

Unfortunately, when running `./postgrest postgrest.conf` this error occurs:

![error](https://user-images.githubusercontent.com/669783/30828620-873d4a4a-a23e-11e7-9a40-84a94dbe3919.png)

**Comment by begriffs** [comment]
Does that byte come from your jwt secret? If so you can save the secret to a separate file and load it with

```
jwt-secret = "@mysecret.txt"
```

or base64 encode it and use

```
secret-is-base64 = true
```

Then again your output looks like it's getting past the parsing of the config file since it knows the server port to bind on. Maybe open a new issue just about this problem if you haven't solved it.

**Comment by barbalex** [comment]
@begriffs 
Thanks for helping. I could solve the problem, see here: https://github.com/begriffs/postgrest/issues/989#issuecomment-332586313

**Comment by barbalex** [comment]
For people finding this later: The ultimate reason this was not working was that `jwt-secret` needed to be at least 32 characters long which at the time of writing is undocumented.
